"""Regression tests for BKT-03: the default G0 gate must be portable and real.

The tests build a synthetic repository so they can drive every failure mode
without depending on the state of the working tree, and they assert the CORRECT
behaviour (a clean in-repo checkout passes; a stale generated artifact, a broken
migration graph or a missing component fails; an unconfigured external blueprint
reports NOT_CONFIGURED) instead of re-demonstrating the original crash.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPTS_DIR = REPO_ROOT / "scripts"

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))


def _load(name: str, filename: str):  # type: ignore[no-untyped-def]
    spec = importlib.util.spec_from_file_location(name, SCRIPTS_DIR / filename)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


core = _load("g0_validate_core", "g0_validate_core.py")

CONTRACT_VERSION = "localdrama.api.2099-01-01.1"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _make_repo(tmp_path: Path, *, expected_heads: list[str] | None = None, contract_version: str = CONTRACT_VERSION) -> Path:
    """Create a self-contained repository that satisfies the in-repo contract."""

    root = tmp_path / "repo"
    _write(root / "apps/api/local_drama/api/contract_version.py", f"API_CONTRACT_VERSION = {contract_version!r}\n")
    _write(
        root / "apps/api/local_drama/main.py",
        '"""Synthetic application factory."""\n\nfrom fastapi import FastAPI\n\n\ndef create_app() -> FastAPI:\n    return FastAPI()\n',
    )
    _write(
        root / "apps/api/local_drama/api/routes/health.py",
        'PATHS = ("/health/live", "/health/ready", "/system/contract")\n',
    )
    _write(root / "apps/api/tests/test_sample.py", "def test_sample() -> None:\n    assert True\n")
    _write(root / "apps/api/requirements-runtime.lock", "pypdf==6.16.2\n")
    _write(root / "apps/api/requirements.lock", "pypdf==6.16.2\n")
    _write(root / "scripts/check_dependency_locks.py", "def main() -> int:\n    return 0\n")
    _write(root / "scripts/generate_client.py", "def main() -> None:\n    return None\n")
    # Migration chain: a single linear branch with exactly one reachable head.
    _write(
        root / "apps/api/alembic/versions/0001_base.py",
        'revision = "0001_base"\ndown_revision = None\n',
    )
    _write(
        root / "apps/api/alembic/versions/0002_next.py",
        'revision = "0002_next"\ndown_revision = "0001_base"\n',
    )
    heads = expected_heads if expected_heads is not None else ["0002_next"]
    _write(
        root / "docs/release/migration-contract.json",
        json.dumps({"schema_version": "localdrama.release-migration-contract.v1", "expected_heads": heads}, indent=2) + "\n",
    )
    _write(
        root / "contracts/config.schema.json",
        json.dumps({"$id": "https://localdramastudio.local/schemas/config.v2.json"}, indent=2) + "\n",
    )
    _write(
        root / "docs/openapi/openapi.json",
        json.dumps(
            {
                "openapi": "3.1.0",
                "paths": {
                    "/api/v1/health/live": {},
                    "/api/v1/health/ready": {},
                    "/api/v1/system/contract": {},
                },
            },
            indent=2,
        )
        + "\n",
    )
    _write(
        root / "apps/web/src/generated/api.ts",
        f"/* Generated by scripts/generate_client.py; do not edit manually. */\nexport const API_CONTRACT_VERSION = {contract_version!r} as const;\n",
    )
    _write(root / "pytest.ini", "[pytest]\ntestpaths = apps/api/tests\n")
    _write(root / "apps/api/pyproject.toml", "[tool.pytest.ini_options]\nmarkers = [\n  \"comfyui: live service\",\n]\n")
    return root


def _spec_for(root: Path, *, api_contract_version: str = CONTRACT_VERSION) -> Path:
    """Write the G0 contract spec used by the synthetic repository."""

    spec = json.loads((REPO_ROOT / "docs" / "release" / "g0-contract.json").read_text(encoding="utf-8"))
    spec["api_contract_version"] = api_contract_version
    spec["migration_heads"]["expected_heads"] = ["0002_next"]
    spec_path = root / "docs" / "release" / "g0-contract.json"
    _write(spec_path, json.dumps(spec, ensure_ascii=False, indent=2) + "\n")
    return spec_path


def test_clean_in_repo_checkout_passes(tmp_path: Path) -> None:
    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.PASS, report.failures
    assert report.mode == "PORTABLE_IN_REPO"
    assert [check.code for check in report.checks] == [
        "REQUIRED_COMPONENTS",
        "SCHEMA_VERSIONS",
        "API_CONTRACT_VERSION",
        "GENERATED_ARTIFACTS",
        "MIGRATION_HEAD",
        "QUALITY_GATES",
    ]


def test_default_check_needs_nothing_outside_the_repo(tmp_path: Path) -> None:
    """The portable gate must pass with no blueprint directory or manifest beside it."""

    nested = tmp_path / "deep" / "nested" / "checkout"
    nested.mkdir(parents=True)
    root = _make_repo(nested)
    assert not (nested / "LocalDramaStudio_Blueprint_v2").exists()
    assert not (nested / "model_manifest.json").exists()
    assert not (nested.parent / "model_manifest.json").exists()
    spec_path = _spec_for(root)
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.PASS, report.failures


def test_missing_component_fails(tmp_path: Path) -> None:
    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    (root / "apps/api/requirements-runtime.lock").unlink()
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.FAIL
    assert any("RUNTIME_LOCK" in finding for finding in report.failures)


def test_stale_api_contract_version_fails(tmp_path: Path) -> None:
    root = _make_repo(tmp_path)
    spec_path = _spec_for(root, api_contract_version="localdrama.api.1999-01-01.1")
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.FAIL
    assert any("contract_version.py exports" in finding for finding in report.failures)


def test_stale_generated_client_fails(tmp_path: Path) -> None:
    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    _write(
        root / "apps/web/src/generated/api.ts",
        "/* stale */\nexport const API_CONTRACT_VERSION = 'localdrama.api.old' as const;\n",
    )
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.FAIL
    assert any("was generated for" in finding for finding in report.failures)


def test_openapi_missing_declared_operation_fails(tmp_path: Path) -> None:
    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    _write(root / "docs/openapi/openapi.json", json.dumps({"openapi": "3.1.0", "paths": {"/api/v1/health/live": {}}}) + "\n")
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.FAIL
    assert any("/api/v1/system/contract" in finding for finding in report.failures)


def test_unreachable_migration_head_fails(tmp_path: Path) -> None:
    """An orphaned branch means the declared head is no longer the only head."""

    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    _write(
        root / "apps/api/alembic/versions/0003_orphan.py",
        'revision = "0003_orphan"\ndown_revision = "0001_base"\n',
    )
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.FAIL
    assert any("reachable alembic heads" in finding or "unreachable" in finding for finding in report.failures)


def test_migration_graph_missing_parent_fails(tmp_path: Path) -> None:
    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    _write(
        root / "apps/api/alembic/versions/0002_next.py",
        'revision = "0002_next"\ndown_revision = "0001_absent"\n',
    )
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.FAIL
    assert any("missing parent" in finding for finding in report.failures)


def test_merge_revision_with_two_parents_is_supported(tmp_path: Path) -> None:
    """Real migrations use multi-parent merge revisions; the graph must accept them."""

    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    _write(
        root / "apps/api/alembic/versions/0003_merge.py",
        'revision = "0003_merge"\ndown_revision = ("0002_next", "0002_side")\n',
    )
    _write(
        root / "apps/api/alembic/versions/0002_side.py",
        'revision = "0002_side"\ndown_revision = "0001_base"\n',
    )
    spec_path.write_text(
        json.dumps(
            {
                **json.loads(spec_path.read_text(encoding="utf-8")),
                "migration_heads": {
                    "source": "docs/release/migration-contract.json",
                    "expected_heads": ["0003_merge"],
                },
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    _write(
        root / "docs/release/migration-contract.json",
        json.dumps({"schema_version": "localdrama.release-migration-contract.v1", "expected_heads": ["0003_merge"]}) + "\n",
    )
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.PASS, report.failures


def test_release_migration_contract_drift_fails(tmp_path: Path) -> None:
    root = _make_repo(tmp_path)
    spec_path = _spec_for(root)
    _write(
        root / "docs/release/migration-contract.json",
        json.dumps({"schema_version": "localdrama.release-migration-contract.v1", "expected_heads": ["0001_base"]}) + "\n",
    )
    report = core.validate_repository(root, spec_path, verify_generator=False)
    assert report.status == core.FAIL
    assert any("expected_heads" in finding for finding in report.failures)


# ---------------------------------------------------------------------------
# Extended (opt-in) external blueprint audit
# ---------------------------------------------------------------------------


def _make_blueprint(tmp_path: Path, *, fr_rows: int = 86, nfr_rows: int = 15, tc_ids: int = 85) -> tuple[Path, Path]:
    blueprint = tmp_path / "LocalDramaStudio_Blueprint_v2"
    blueprint.mkdir(parents=True, exist_ok=True)
    spec = json.loads((REPO_ROOT / "docs/release/g0-contract.json").read_text(encoding="utf-8"))["external_blueprint_audit"]
    inventory_numbers = {1, 10}
    for number in spec["in_scope_documents"]:
        if number in inventory_numbers:
            continue
        (blueprint / f"{number:02d}_document.md").write_text(f"# document {number}\n", encoding="utf-8")
    requirement_rows = "\n".join(
        [f"| FR-ABC-{index:03d} | row |" for index in range(1, fr_rows + 1)]
        + [f"| NFR-ABC-{index:03d} | row |" for index in range(1, nfr_rows + 1)]
    )
    (blueprint / spec["master_inventory"]["requirements_document"]).write_text(requirement_rows + "\n", encoding="utf-8")
    test_rows = "\n".join(f"- TC-ABC-{index:03d}" for index in range(1, tc_ids + 1))
    (blueprint / spec["master_inventory"]["tests_document"]).write_text(test_rows + "\n", encoding="utf-8")
    (blueprint / spec["migration_document"]).write_text("# migration\n", encoding="utf-8")
    manifest = tmp_path / "model_manifest.json"
    manifest.write_text(
        json.dumps({"manifest_version": "test", "authoritative_current_state": {"route_status": {}}}) + "\n",
        encoding="utf-8",
    )
    return blueprint, manifest


def test_extended_audit_is_not_configured_without_external_inputs() -> None:
    report = core.audit_blueprint(None, None)
    assert report.mode == "EXTENDED_BLUEPRINT_AUDIT"
    assert report.status != core.PASS
    check = report.checks[0]
    assert check.status == core.NOT_CONFIGURED
    assert "UAT" in check.detail


def test_extended_audit_cli_rejects_a_single_external_input(tmp_path: Path) -> None:
    completed = subprocess.run(
        [sys.executable, str(SCRIPTS_DIR / "g0_validate.py"), "--blueprint-root", str(tmp_path / "blueprint")],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    # Supplying only one of the two external inputs is an explicit usage error.
    assert completed.returncode == 2
    assert "--manifest" in completed.stderr


def test_extended_audit_cli_reports_not_configured_for_absent_inputs(tmp_path: Path) -> None:
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPTS_DIR / "g0_validate.py"),
            "--blueprint-root",
            str(tmp_path / "no-blueprint"),
            "--manifest",
            str(tmp_path / "no-manifest.json"),
        ],
        capture_output=True,
        text=True,
        cwd=REPO_ROOT,
    )
    # Neither input exists, so the extended audit fails instead of faking a PASS.
    assert completed.returncode == 1
    assert "EXTERNAL_BLUEPRINT_AUDIT=FAIL" in completed.stdout


def test_extended_audit_passes_with_a_complete_blueprint(tmp_path: Path) -> None:
    blueprint, manifest = _make_blueprint(tmp_path, fr_rows=86, nfr_rows=15, tc_ids=85)
    report = core.audit_blueprint(blueprint, manifest)
    assert report.status == core.PASS, report.failures


def test_extended_audit_fails_on_inventory_drift(tmp_path: Path) -> None:
    blueprint, manifest = _make_blueprint(tmp_path, fr_rows=12, nfr_rows=15, tc_ids=85)
    report = core.audit_blueprint(blueprint, manifest)
    assert report.status == core.FAIL
    assert any("master inventory drift" in finding for finding in report.failures)


def test_extended_audit_fails_when_inputs_are_absent(tmp_path: Path) -> None:
    report = core.audit_blueprint(tmp_path / "nope", tmp_path / "missing_manifest.json")
    assert report.status == core.FAIL
    assert any("does not exist" in finding for finding in report.failures)


def test_extended_audit_rejects_ambiguous_in_scope_documents(tmp_path: Path) -> None:
    blueprint, manifest = _make_blueprint(tmp_path)
    (blueprint / "00_duplicate.md").write_text("# duplicate\n", encoding="utf-8")
    with pytest.raises(core.G0ValidationError, match="exactly one in-scope document"):
        core.audit_blueprint(blueprint, manifest)


def test_spec_rejects_a_foreign_document(tmp_path: Path) -> None:
    bad = tmp_path / "g0-contract.json"
    bad.write_text(json.dumps({"schema_version": "something.else"}) + "\n", encoding="utf-8")
    with pytest.raises(core.G0ValidationError, match="localdrama.g0-contract.v1"):
        core.load_spec(bad)


def test_contract_paths_may_not_escape_the_repository(tmp_path: Path) -> None:
    with pytest.raises(core.G0ValidationError, match="escapes the repository root"):
        core._resolve(tmp_path, "../outside.json")


def test_committed_spec_covers_the_real_repository_components() -> None:
    """The committed spec must describe the real repository, whatever the gate status."""

    spec = core.load_spec(REPO_ROOT / "docs" / "release" / "g0-contract.json")
    assert core.check_components(REPO_ROOT, spec).status == core.PASS
    assert core.check_schema_versions(REPO_ROOT, spec).status == core.PASS
    assert core.check_api_contract_version(REPO_ROOT, spec).status == core.PASS
    assert core.check_quality_gates(REPO_ROOT, spec).status == core.PASS
