from __future__ import annotations

from local_drama.domain.errors import DomainRuleError
from local_drama.errors import ApiError


def api_error_from_domain(error: DomainRuleError) -> ApiError:
    if error.code in {"AUTOMATION_TOKEN_REQUIRED", "AUTOMATION_TOKEN_INVALID", "AUTOMATION_SCOPE_FORBIDDEN", "AUTOMATION_PROJECT_FORBIDDEN"}:
        status = 403
    elif error.code.endswith("_NOT_FOUND") or error.code in {"PROJECT_NOT_FOUND", "SHOT_NOT_FOUND"}:
        status = 404
    elif error.code in {
        "MP_PROFILE_CROSSWALK_FIELDS_REQUIRED",
        "MP_PROFILE_CROSSWALK_LEGACY_NOT_PUBLISHED",
        "MP_PROFILE_CROSSWALK_LEGACY_CAPABILITY_UNKNOWN",
        "MP_PROFILE_CROSSWALK_V2_NOT_PUBLISHED",
        "MP_PROFILE_CROSSWALK_CAPABILITY_MISMATCH",
        "MP_PROFILE_CROSSWALK_PARAMETER_CONTRACT_MISMATCH",
    }:
        status = 400
    elif error.code in {
        "PIPELINE_ALREADY_RUNNING",
        "PIPELINE_STATE_INVALID",
        "MP_PROFILE_CROSSWALK_ACTIVE_MAPPING_EXISTS",
        "MP_PROFILE_CROSSWALK_NOT_APPROVED",
        "REVISION_CONFLICT",
        "INVALID_STATE_TRANSITION",
        "PROJECT_CODE_EXISTS",
        "REVIEW_STALE",
        "REVIEW_BATCH_STALE",
        "REVIEW_BATCH_TOKEN_INVALID",
        "CONTINUITY_IMPACT_CONFIRMATION_REQUIRED",
        "CONTINUITY_IMPACT_STALE",
        "MACHINE_QC_REQUIRED",
        "PROFILE_NOT_PUBLISHED",
        "IDEMPOTENCY_PAYLOAD_MISMATCH",
        "FRAME_BRIDGE_IDEMPOTENCY_MISMATCH",
        "DIALOGUE_IDEMPOTENCY_MISMATCH",
        "AUDIO_ADOPTION_IDEMPOTENCY_MISMATCH",
        "DIALOGUE_TEXT_REVISION_CONFLICT",
        "LEASE_TOKEN_INVALID",
        "LEASE_EXPIRED",
        "ATTEMPT_NOT_ACTIVE",
        "JOB_NOT_RETRYABLE",
        "INVALID_JOB_DEPENDENCY",
        "IMAGE_CONTENT_REQUIRES_THUMBNAIL",
        "STORY_ASSET_CODE_CONFLICT",
        "STORY_ASSET_REVISION_CONFLICT",
        "STORY_ASSET_ALREADY_BOUND",
        "STORY_ASSET_ALREADY_ARCHIVED",
        "GENERATION_PREFERENCE_REVISION_CONFLICT",
        "QC_POLICY_REVISION_CONFLICT",
        "QC_AUTO_REROLL_ALREADY_ATTACHED",
        "SHOT_GROUP_REVISION_CONFLICT",
        "SHOT_GROUP_CODE_EXISTS",
        "SHOT_EDIT_PLAN_STALE",
        "BEAT_REPLAN_PLAN_STALE",
        "TIMELINE_REFRESH_PLAN_STALE",
        "SHOT_REVISION_CONFLICT",
        "ASSET_PROPOSAL_REVISION_CONFLICT",
        "ASSET_PROPOSAL_ALREADY_DECIDED",
        "MEDIA_DERIVATIVE_NOT_READY",
        "CONFIGURATION_CHANGED",
        "EPISODE_PROJECT_MISMATCH",
        "EPISODE_PRODUCTION_IDEMPOTENCY_MISMATCH",
        "EPISODE_PRODUCTION_RUN_REVISION_CONFLICT",
        "REVIEW_IDEMPOTENCY_PAYLOAD_MISMATCH",
        "REVIEW_REVISION_CONFLICT",
        "REVIEW_DECISION_REVISION_CONFLICT",
        "REVIEW_DECISION_ALREADY_REVOKED",
        "AUDIO_IDEMPOTENCY_PAYLOAD_MISMATCH",
        "AUDIO_MIX_REVISION_CONFLICT",
        "AUDIO_TRACK_REVISION_CONFLICT",
        "TIMELINE_IDEMPOTENCY_PAYLOAD_MISMATCH",
        "TIMELINE_REVISION_CONFLICT",
        "TIMELINE_UPSTREAM_CONFLICT",
        "TIMELINE_VIDEO_SELECTION_CONFLICT",
    }:
        status = 409
    else:
        status = 422
    return ApiError(error.code, error.message, status_code=status, details=error.details, suggested_action=error.suggested_action)
