"""Application ports for the Asset Bible bounded context.

New application code depends on these protocols, never on concrete
infrastructure (see docs/xinjihua/02 §13 and the P0-03 architecture guard).
SQLite is only one implementation of these ports.
"""

from __future__ import annotations

from typing import Any, Protocol


class AssetBibleUnitOfWork(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class AssetBibleRepository(Protocol):
    """Persistence boundary for story asset states, references, and bindings."""

    def get_asset(self, asset_id: str) -> dict[str, Any]: ...
    def list_assets(self, project_id: str, kind: str | None = None) -> list[dict[str, Any]]: ...
    def asset_project_id(self, asset_id: str) -> str | None: ...
    def media_project_id(self, media_version_id: str) -> str | None: ...
    def shot_project_id(self, shot_id: str) -> str | None: ...
    def episode_project_id(self, episode_id: str) -> str | None: ...
    def update_asset_canonical(self, story_asset_id: str, media_version_id: str) -> None: ...

    def create_state(
        self,
        *,
        project_id: str,
        story_asset_id: str,
        code: str,
        label: str,
        state_kind: str,
        description: str,
        state_json: dict[str, Any],
        actor: str,
    ) -> dict[str, Any]: ...
    def update_state(self, state_id: str, expected_revision: int, *, label: str | None, description: str | None, state_json: dict[str, Any] | None, actor: str) -> dict[str, Any]: ...
    def list_states(self, story_asset_id: str) -> list[dict[str, Any]]: ...
    def get_state(self, state_id: str) -> dict[str, Any] | None: ...
    def archive_state(self, state_id: str, expected_revision: int, actor: str) -> dict[str, Any]: ...

    def add_reference(
        self,
        *,
        project_id: str,
        story_asset_id: str,
        asset_state_id: str | None,
        media_version_id: str,
        reference_kind: str,
        label: str,
        priority: int,
        is_locked: bool,
        yaw_deg: float | None,
        pitch_deg: float | None,
        actor: str,
    ) -> dict[str, Any]: ...
    def update_reference(self, reference_id: str, expected_revision: int, *, label: str | None, priority: int | None, is_locked: bool | None, yaw_deg: float | None, pitch_deg: float | None, actor: str) -> dict[str, Any]: ...
    def list_references(self, story_asset_id: str, asset_state_id: str | None = None) -> list[dict[str, Any]]: ...
    def get_reference(self, reference_id: str) -> dict[str, Any] | None: ...
    def archive_reference(self, reference_id: str, expected_revision: int, actor: str) -> dict[str, Any]: ...

    def set_episode_asset_state(self, *, episode_id: str, story_asset_id: str, asset_state_id: str, actor: str) -> dict[str, Any]: ...
    def episode_asset_state(self, episode_id: str, story_asset_id: str) -> dict[str, Any] | None: ...
    def set_shot_asset_state(self, *, shot_id: str, asset_id: str, asset_state_id: str, actor: str) -> dict[str, Any]: ...
    def shot_asset_states(self, shot_id: str) -> list[dict[str, Any]]: ...

    def audit(self, *, actor: str, role_context: str, action: str, subject_type: str, subject_id: str, summary: str, metadata: dict[str, Any]) -> None: ...

    def voice_binding(self, asset_id: str) -> dict[str, Any] | None: ...
    def asset_shots(self, asset_id: str) -> list[dict[str, Any]]: ...
    def multiview_generations(self, asset_id: str) -> list[dict[str, Any]]: ...
    def expression_generations(self, asset_id: str) -> list[dict[str, Any]]: ...
    def detail_generations(self, asset_id: str) -> list[dict[str, Any]]: ...
