from __future__ import annotations

from typing import Any, Protocol


class DirectorRecipeRepository(Protocol):
    def project_exists(self, project_id: str) -> bool: ...
    def create_recipe(self, *, project_id: str, code: str, title: str, recipe: dict[str, Any], recipe_hash: str, reason: str, actor: str) -> dict[str, Any]: ...
    def create_version(self, *, project_id: str, recipe_id: str, recipe: dict[str, Any], recipe_hash: str, reason: str, actor: str) -> dict[str, Any]: ...
    def bind(self, *, project_id: str, recipe_version_id: str, reason: str, actor: str, expected_revision: int | None) -> dict[str, Any]: ...
    def list_recipes(self, project_id: str) -> list[dict[str, Any]]: ...
    def get_recipe(self, project_id: str, recipe_id: str) -> dict[str, Any] | None: ...
    def current_binding(self, project_id: str) -> dict[str, Any] | None: ...
