"""Persistence port for versioned generation preferences."""

from __future__ import annotations

from typing import Any, Protocol


class GenerationPreferenceRepository(Protocol):
    def project_exists(self, project_id: str) -> bool: ...
    def owner_project_id(self, owner_type: str, owner_id: str) -> str | None: ...
    def shot_episode_id(self, shot_id: str) -> str | None: ...
    def profile(self, profile_version_id: str) -> dict[str, Any] | None: ...
    def auto_profile(self, capability: str) -> dict[str, Any] | None: ...
    def recent_terminal_attempts(self, profile_version_id: str, *, limit: int) -> dict[str, Any]: ...
    def current_preference(self, project_id: str, owner_type: str, owner_id: str, capability: str) -> dict[str, Any] | None: ...
    def put_preference(
        self, *, project_id: str, owner_type: str, owner_id: str, capability: str,
        execution_profile_version_id: str | None, resolution_mode: str,
        settings: dict[str, Any], reason: str, actor: str,
        expected_revision: int | None,
    ) -> dict[str, Any]: ...
    def list_current(self, project_id: str) -> list[dict[str, Any]]: ...
