"""Persistence port for immutable QC policy versions and variant dispositions."""

from __future__ import annotations

from typing import Any, Protocol


class QcPolicyRepository(Protocol):
    def owner_project_id(self, owner_type: str, owner_id: str) -> str | None: ...
    def shot_episode_id(self, shot_id: str) -> str | None: ...
    def variant_context(self, variant_id: str) -> dict[str, Any] | None: ...
    def machine_check(self, run_id: str) -> dict[str, Any] | None: ...
    def current_policy(self, project_id: str, owner_type: str, owner_id: str, stage: str) -> dict[str, Any] | None: ...
    def list_current(self, project_id: str) -> list[dict[str, Any]]: ...
    def put_policy(
        self, *, project_id: str, owner_type: str, owner_id: str, stage: str,
        policy: dict[str, Any], max_auto_rerolls: int, auto_reroll_categories: list[str],
        reason: str, actor: str, expected_revision: int | None,
    ) -> dict[str, Any]: ...
    def auto_retry_count(self, variant_id: str) -> int: ...
    def qc_link(self, variant_id: str, machine_check_run_id: str) -> dict[str, Any] | None: ...
    def record_qc_link(
        self, *, variant_id: str, machine_check_run_id: str, policy_version_id: str,
        category: str, disposition: str, retry_ordinal: int, reason: str, actor: str,
    ) -> dict[str, Any]: ...
    def attach_child(self, link_id: str, parent_variant_id: str, child_variant_id: str, actor: str) -> dict[str, Any]: ...
