import { useMemo, useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { createProject, planProjectCreation, type Project, type ProjectCreatePayload } from "../../generated/api";

export function ProjectCreateWizard({ onCreated }: { onCreated: (project: Project) => void }) {
  const [open, setOpen] = useState(false);
  const [step, setStep] = useState(1);
  const [values, setValues] = useState({ code: "", title: "", episodes: "", duration: "", ratio: "", fpsNum: "", fpsDen: "", accepted: false });
  const payload = useMemo<ProjectCreatePayload>(() => ({ code: values.code.trim(), title: values.title.trim(), episode_count: Number(values.episodes), target_duration_ms: Number(values.duration) * 1000, aspect_ratio: values.ratio.trim(), fps: { numerator: Number(values.fpsNum), denominator: Number(values.fpsDen) }, allow_unconfigured_capabilities: values.accepted }), [values]);
  const plan = useMutation({ mutationFn: () => planProjectCreation(payload), onSuccess: () => setStep(4) });
  const create = useMutation({ mutationFn: () => createProject(payload), onSuccess: ({ project }) => onCreated(project) });
  const update = (key: keyof typeof values, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  if (!open) return <button onClick={() => setOpen(true)}>新建项目</button>;
  return <section className="project-create-wizard" aria-labelledby="project-create-title">
    <div className="panel-heading"><div><p className="eyebrow">步骤 {step}/4</p><h3 id="project-create-title">新建版本化项目</h3></div><button className="secondary" onClick={() => setOpen(false)}>关闭</button></div>
    {step === 1 && <div className="wizard-grid"><label>项目标题<input value={values.title} onChange={(event) => update("title", event.target.value)} /></label><label>项目 code<input value={values.code} onChange={(event) => update("code", event.target.value)} placeholder="小写字母、数字、下划线" /></label><label>集数<input type="number" min="1" value={values.episodes} onChange={(event) => update("episodes", event.target.value)} /></label><button disabled={!values.title.trim() || !values.code.trim() || Number(values.episodes) < 1} onClick={() => setStep(2)}>下一步：制作规格</button></div>}
    {step === 2 && <div className="wizard-grid"><label>画幅比例<input value={values.ratio} onChange={(event) => update("ratio", event.target.value)} placeholder="例如 9:16（不自动选择）" /></label><label>fps 分子<input type="number" min="1" value={values.fpsNum} onChange={(event) => update("fpsNum", event.target.value)} /></label><label>fps 分母<input type="number" min="1" value={values.fpsDen} onChange={(event) => update("fpsDen", event.target.value)} /></label><label>目标集时长（秒）<input type="number" min="1" value={values.duration} onChange={(event) => update("duration", event.target.value)} /></label><div className="action-row"><button className="secondary" onClick={() => setStep(1)}>上一步</button><button disabled={!values.ratio.trim() || Number(values.fpsNum) < 1 || Number(values.fpsDen) < 1 || Number(values.duration) < 1} onClick={() => setStep(3)}>下一步：本地能力</button></div></div>}
    {step === 3 && <div className="wizard-confirm"><p>当前向导不会暗选 H3、Profile、ProductionPlan 或交付目标。</p><label className="check-label"><input type="checkbox" checked={values.accepted} onChange={(event) => update("accepted", event.target.checked)} />稍后逐项配置，并接受项目在此之前保持阻塞</label><div className="action-row"><button className="secondary" onClick={() => setStep(2)}>上一步</button><button disabled={!values.accepted || plan.isPending} onClick={() => plan.mutate()}>{plan.isPending ? "预检中…" : "运行存储与配置预检"}</button></div>{plan.error && <p role="alert">{plan.error.message}</p>}</div>}
    {step === 4 && plan.data && <div className="wizard-preview"><strong>{plan.data.plan.status}</strong><p>目标目录：{plan.data.plan.target_root_rel} · 预计最少 {plan.data.plan.estimated_bytes} bytes</p><ul>{plan.data.plan.checks.map((check) => <li key={check.code}>{check.passed ? "PASS" : "FAIL"} · {check.code}</li>)}</ul><p>创建后阻塞：{plan.data.plan.configuration_blockers.join("、")}</p>{create.error && <p role="alert">{create.error.message}</p>}<div className="action-row"><button className="secondary" onClick={() => setStep(3)}>返回修改</button><button disabled={plan.data.plan.status === "BLOCKED" || create.isPending} onClick={() => create.mutate()}>{create.isPending ? "创建中…" : "确认创建 DRAFT"}</button></div></div>}
  </section>;
}
