import { useState } from "react";
import { commitFormalSelection, preflightFormalSelection, type FormalSelectionCandidate, type FormalSelectionPlan } from "../../generated/api";

export function FormalSelectionPanel({ projectId, candidates, onChanged }: { projectId: string; candidates: FormalSelectionCandidate[]; onChanged?: () => void }) {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [plan, setPlan] = useState<FormalSelectionPlan | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const ids = [...selected];
  const toggle = (id: string) => { setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); setPlan(null); setMessage(null); };
  const preflight = async () => { setBusy("preflight"); setError(null); setMessage(null); try { setPlan((await preflightFormalSelection(projectId, ids)).plan); } catch (caught) { setError(String(caught)); } finally { setBusy(null); } };
  const commit = async () => { if (!plan || plan.status !== "READY") return; setBusy("commit"); setError(null); setMessage(null); try { const result = await commitFormalSelection(projectId, ids, plan.plan_hash); setMessage(`已原子选择 ${result.result.items.length} 个正式视频；历史选择未删除。`); setSelected(new Set()); setPlan(null); onChanged?.(); } catch (caught) { setError(String(caught)); } finally { setBusy(null); } };
  return <section className="panel formal-selection-panel" aria-labelledby="formal-selection-title"><div className="panel-heading"><div><p className="eyebrow">FR-VID-007 · 交付选择</p><h3 id="formal-selection-title">批量正式交付选择</h3></div><span className="status-pill neutral">全量预检 · 原子提交</span></div><p className="muted">只列出当前项目 FORMAL 视频；每项必须有最新人工 APPROVED、approved_version 指针和 VERIFIED hash。任何冲突都逐项返回，不能静默部分成功。</p>{candidates.length === 0 ? <p className="empty-state">当前没有正式视频候选。</p> : <div className="configuration-table" role="table" aria-label="正式交付候选"><div className="configuration-row configuration-header" role="row"><strong>选择</strong><strong>候选</strong><strong>审核 / 完整性</strong><strong>版本</strong></div>{candidates.map((candidate) => <div className="configuration-row" role="row" key={candidate.media_version_id}><label><input type="checkbox" checked={selected.has(candidate.media_version_id)} onChange={() => toggle(candidate.media_version_id)} /></label><span><img className="thumbnail-inline" src={`/api/v1/media-versions/${encodeURIComponent(candidate.media_version_id)}/thumbnail?size=small&frame=poster`} alt="正式视频海报缩略图" width="96" height="54" loading="lazy" decoding="async" /><code>{candidate.media_version_id.slice(0, 12)}…</code></span><span>{candidate.decision ?? "未审核"} · {candidate.is_stale ? "STALE" : "最新"} · {candidate.integrity_status}</span><span>{candidate.approved_version_id === candidate.media_version_id ? "approved_version" : "未指向当前"}</span></div>)}</div>}
    <div className="action-row"><button className="secondary" type="button" onClick={() => void preflight()} disabled={busy !== null || ids.length === 0}>{busy === "preflight" ? "预检中…" : `预检 ${ids.length} 项`}</button><button className="primary-action" type="button" onClick={() => void commit()} disabled={busy !== null || !plan || plan.status !== "READY"}>{busy === "commit" ? "提交中…" : "确认原子选择"}</button>{plan && <span className={plan.status === "READY" ? "ok-text" : "blocker-text"}>计划 {plan.status} · {plan.items.filter((item) => item.status === "READY").length}/{plan.items.length} READY</span>}</div>
    {plan?.status === "BLOCKED" && <div className="review-guidance">{plan.items.filter((item) => item.status === "BLOCKED").map((item) => <p key={item.media_version_id}>{item.media_version_id.slice(0, 12)}…：{item.blockers.join("、")}</p>)}</div>}{message && <p className="review-success" role="status">{message}</p>}{error && <p className="inline-error" role="alert">批量正式选择失败：{error}</p>}
  </section>;
}
