"""Generate the committed OpenAPI snapshot and a small typed TS client from the app."""

from __future__ import annotations

import json
import sys
from importlib import import_module
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "apps" / "api"
sys.path.insert(0, str(API_ROOT))

app = import_module("local_drama.main").app


def main() -> None:
    spec = app.openapi()
    openapi_path = ROOT / "docs" / "openapi" / "openapi.json"
    openapi_path.write_text(
        json.dumps(spec, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    client_path = ROOT / "apps" / "web" / "src" / "generated" / "api.ts"
    client_source = """/* Generated by scripts/generate_client.py; do not edit manually. */
export type HealthCheck = { status: string; checks: Record<string, string> };
export type LocalSession = { token: string; mode: 'LOCAL_ONLY' };
export type SystemContract = Record<string, string>;
export type Project = { id: string; code: string; title: string; status: string; revision: number; [key: string]: unknown };
export type MasterScene = { id: string; project_id: string; code: string; title: string; location: string | null; time_of_day: string | null; revision: number };
export type EpisodeSceneRange = { id: string; episode_id: string; scene_id: string; ordinal: number; source_start: number; source_end: number; source_label: string | null; scene_code: string; scene_title: string; location: string | null; time_of_day: string | null };
export type ContinuityShot = { position: 'previous' | 'current' | 'next'; id: string; code: string; order_key: string; status: string; target_duration_ms: number; revision: { id: string | null; revision_no: number | null; is_frozen: boolean }; facets: Record<string, unknown | null>; missing_facets: string[]; references: Array<{ media_asset_id: string; media_version_id: string; purpose: string; media_kind: string; selection_state: 'APPROVED' | 'SELECTED'; version_no: number; stage: string; integrity_status: string }> };
export type ContinuityContext = { episode_id: string; selected_shot_id: string; shots: { previous: ContinuityShot | null; current: ContinuityShot; next: ContinuityShot | null }; transitions: Array<Record<string, unknown>>; read_only: true; runtime_contacted: false; network_contacted: false; mutated: false };
export type CreativeEntry = { id: string; project_id: string; kind: string; code: string; title: string; current_revision_id: string; revision_no: number; content_hash: string; change_note: string; content: Record<string, unknown>; revision: number };
export type CreativeEntryRevision = { id: string; entry_id: string; revision_no: number; parent_revision_id: string | null; restored_from_revision_id: string | null; content_hash: string; change_note: string; content: Record<string, unknown>; created_at: string };
export type ScriptBreakdownDraft = { id: string; project_id: string; source_document_version_id: string; import_session_id: string; status: string; source_document_code: string; source_document_title: string; draft: { scenes?: Array<Record<string, unknown>> }; confidence: { profile_version_id?: string; model?: string; confidence?: { overall?: number; notes?: string[] }; questions?: string[]; source_passages?: Array<{ scene_no: number; quote: string; source_start: number; source_end: number }> }; profile_version_id: string | null; evidence_status: 'COMPLETE' | 'LEGACY_INCOMPLETE'; application_status: 'NOT_APPLIED'; automatic_apply: false; requires_human_action: true; created_at: string };
export type ProjectCreatePayload = { code: string; title: string; season_count: number; episode_count: number; target_duration_ms: number; aspect_ratio: string; width: number; height: number; fps: { numerator: number; denominator: number }; primary_language: string; subtitle_mode: 'NONE' | 'SIDECAR' | 'BURN_IN' | 'BOTH'; subtitle_language?: string; allow_unconfigured_capabilities: boolean; production_plan?: { code: string; title: string; plan: Record<string, unknown> }; profile_bindings?: Array<{ capability: string; profile_version_id: string }>; delivery_target?: { code: string; title: string; spec: Record<string, unknown> } };
export type ProjectCreationPlan = { status: 'READY' | 'READY_WITH_CONFIGURATION_BLOCKERS' | 'BLOCKED'; checks: Array<{ code: string; passed: boolean; free_bytes?: number; required_bytes?: number }>; blockers: string[]; configuration_blockers: string[]; accepted_unconfigured: boolean; target_root_rel: string; estimated_bytes: number; structure: { season_count: number; episode_count_per_season: number; total_episode_count: number }; presentation: Record<string, unknown>; would_create_project: true; mutated: false; runtime_contacted: false; network_contacted: false };
export type ProjectPackageExport = { status: 'EXPORTED'; project_id: string; rel_path: string; byte_size: number; sha256: string; entry_count: number; expanded_bytes: number; reused: boolean; database_mutated: false; runtime_contacted: false; network_contacted: false };
export type ProjectPackageDryRun = { status: 'READY_REBIND_EXISTING' | 'IDENTITY_CONFLICT' | 'READY_IMPORT' | 'BLOCKED'; project_id: string; project_code: string; entry_count: number; expanded_bytes: number; free_bytes: number; blockers: string[]; conflict_options: string[]; would_import: false; mutated: false; runtime_contacted: false; network_contacted: false };
export type ProjectPackageStaging = { status: 'STAGED'; stage_token: string; source_name: string; byte_size: number; sha256: string; reused: boolean; source_retained: true; dry_run: ProjectPackageDryRun; database_mutated: false; runtime_contacted: false; network_contacted: false };
export type ProjectPackageCommit = { status: 'IMPORTED' | 'REBOUND'; identity_mode: 'REBIND_EXISTING' | 'IMPORT_AS_COPY_REWRITE_IDENTITY'; project_id: string; project_code: string; stage_token: string; staged_package_retained: true; runtime_contacted: false; network_contacted: false; counts?: Record<string, number>; database_structure_changed?: false };
export type Profile = { id: string; code: string; title: string; version_id: string; capability: string; status: string; [key: string]: unknown };
export type ProfileContract = { input_contract: Record<string, unknown>; parameter_schema: Record<string, unknown>; output_contract: Record<string, unknown>; resource_policy: Record<string, unknown> };
export type ProfileValidation = { id: string; profile_version_id?: string; contract_hash: string; status: 'PASS' | 'FAIL'; checks: Array<{ code: string; passed: boolean; label?: string }>; runtime_contacted?: false; network_contacted?: false };
export type ProfileVersionDetail = { id: string; execution_profile_id: string; code: string; title: string; version_no: number; capability: string; status: string; revision: number; input_contract: Record<string, unknown>; parameter_schema: Record<string, unknown>; output_contract: Record<string, unknown>; resource_policy: Record<string, unknown>; capability_contract?: Record<string, unknown>; contract_hash: string; validation: ProfileValidation | null };
export type DiagnosticRun = { id: string; status: string; checks: Array<{ code: string; category: string; status: string; observed: Record<string, unknown> }> };
export type ReviewTemplate = { id: string; code: string; version_no: number; subject_type: string; items: Array<{ id: string; label: string; required: boolean }> };
export type ReviewInboxItem = { media_version_id: string; media_asset_id: string; project_id: string; media_kind: string; stage: string; decision: string | null; is_stale: number | null; [key: string]: unknown };
export type VideoAnnotation = { id: string; media_version_id: string; timecode_ms: number; category: string; comment: string; snapshot_media_version_id: string | null; rework_job_id: string | null; created_at: string; created_by: string; schema_version: 'v2' };
export type FrameAnchor = { id: string; source_media_version_id: string; source_time_us: number; source_frame_index: number; extracted_media_version_id: string; role_hint: string; sha256: string; requested_time_us: number | null; resolved_time_us: number; source_sha256: string; extraction_method: string; [key: string]: unknown };
export type KeyframeCandidate = { id: string; media_asset_id: string; project_id: string; owner_type: 'SHOT'; owner_id: string; media_kind: 'IMAGE'; stage: 'KEYFRAME'; parent_version_id: string; duplicate: boolean; [key: string]: unknown };
export type ContactSheetExport = { schema_version: 'localdrama.contact-sheet.v1'; status: 'EXPORTED'; rel_path: string; manifest_rel_path: string; contact_sheet_rel_path: string; export_hash: string; item_count: number; reused: boolean; database_mutated: false; runtime_contacted: false; network_contacted: false };
export type TimelineExport = { schema_version: 'localdrama.timeline-export.v1'; status: 'EXPORTED'; rel_path: string; manifest_rel_path: string; files: Array<{ rel_path: string; byte_size: number; sha256: string }>; export_hash: string; reused: boolean; database_mutated: false; runtime_contacted: false; network_contacted: false };
export type Job = { id: string; type: string; project_id: string; state: string; channel: string; priority: number; max_attempts: number; revision: number; [key: string]: unknown };
export type GenerationIntent = { id: string; project_id: string; owner_type: string; owner_id: string; purpose: string; creative_goal: string; [key: string]: unknown };
export type VariantInput = { role: string; media_version_id: string; ordinal?: number };
export type GenerationVariantDraft = { intent_id: string; variant_type: string; parent_variant_id?: string | null; branch_reason: string; prompt_revision_id?: string | null; profile_version_id: string; parameter_set?: Record<string, unknown>; seed_policy: string; explicit_seed?: number | null; provider_random_nonce?: string | null; bindings?: VariantInput[] };
export type GenerationVariant = { id: string; intent_id: string; variant_no: number; variant_type: string; parent_variant_id: string | null; recipe_hash: string; status: string; bindings: Array<Record<string, unknown>>; [key: string]: unknown };
export type GenerationVariantPlan = { intent_id: string; status: 'READY'; plan_hash: string; recipe_hash: string; dependencies: Record<string, unknown>; would_persist_variant: false; would_create_job: false };
export type PromptRevision = { id: string; prompt_id: string; revision_no: number; parent_revision_id: string | null; content_text: string; structured: Record<string, unknown>; content_hash: string; status: 'FROZEN'; [key: string]: unknown };
export type GenerationExperiment = { id: string; intent_id: string; title: string; status: 'DRAFT' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED'; plan_hash: string; cell_count: number; expanded_count: number; remaining_count: number; [key: string]: unknown };
export type GenerationExperimentEstimate = { experiment_id: string; cell_count: number; expanded_count: number; remaining_count: number; max_parallel: number; estimated_cpu_seconds: number; estimated_disk_bytes: number; gpu_slots: number; status: string; plan_hash: string; confirmation_required: boolean; large_matrix_confirmation_required: boolean; large_matrix_confirmation_threshold: number; would_create_jobs: false };
export type LocalLLMStatus = { status: string; base_url: string; model: string | null; error_code?: string; available_models?: string[]; model_present?: boolean };
export type H3Runtime = { status: string; release_root?: string; missing_sidecars?: string[]; missing_model_files?: string[]; required_sidecars?: string[] };
export type G6Readiness = { gate: 'G6'; status: 'PASS' | 'IN_PROGRESS'; project_id: string; checks: Array<{ code: string; passed: boolean; count?: number }>; next_required_action: string | null; evidence: Record<string, unknown>; mutated: false };
export type G7Readiness = { gate: 'G7'; status: 'PASS' | 'IN_PROGRESS'; project_id: string; checks: Array<{ code: string; passed: boolean; count?: number }>; next_required_action: string | null; evidence: Record<string, unknown>; runtime_contacted: false; network_contacted: false; mutated: false };
export type G8Readiness = { gate: 'G8'; status: 'PASS' | 'IN_PROGRESS'; project_id: string; episode: { id: string; code: string; title: string }; checks: Array<{ code: string; passed: boolean; count?: number; required?: number; detail: string; required_tracks?: string[]; observed_tracks?: string[] }>; next_required_action: string | null; evidence: { timeline_revision_id: string | null; render_id: string | null; delivery_id: string | null; audio_tracks: string[]; subtitle_revision_count: number }; observed_at: string; runtime_contacted: false; network_contacted: false; mutated: false };
export type G9Readiness = { gate: 'G9'; status: 'PASS' | 'IN_PROGRESS'; project_id: string; episode: { id: string; code: string; title: string }; checks: Array<{ code: string; passed: boolean; count?: number; detail: string; required_range?: number[] }>; next_required_action: string | null; evidence: { production_total_shots: number; production_visible_nodes: number; persisted_layout_count: number; persisted_preflight_count: number; performance_uat: { path: string; observed_at?: string | null } | null; accessibility_route_uat: { path: string; observed_at?: string | null } | null; automated_fixture: string }; observed_at: string; runtime_contacted: false; network_contacted: false; mutated: false };
export type ModelCompatibilityReport = { id: string; model_artifact_id: string; path_ref: string; sha256: string; byte_size: number; header: Record<string, unknown>; quantization: Record<string, unknown>; license_status: string; report_status: 'PASS' | 'BLOCKED'; blockers: string[]; license_evidence_id?: string | null; runtime_contacted: false; network_contacted: false };
export type ModelCompatibilitySnapshot = { reports: Array<{ artifact_id: string; code: string; kind: string; machine_path_ref: string; artifact_status: string; artifact_sha256: string | null; report_id: string | null; report_sha256: string | null; byte_size: number | null; quantization: Record<string, unknown>; license_status: string | null; report_status: 'PASS' | 'BLOCKED' | null; blockers: string[]; report_created_at: string | null; license_evidence_id: string | null; license_path_rel: string | null; has_report: boolean; has_license_evidence: boolean }>; summary: { artifact_count: number; reported_count: number; pass_count: number; blocked_count: number; missing_license_evidence_count: number }; runtime_contacted: false; network_contacted: false; mutated: false };
export type ProjectConfiguration = { project: { id: string; code: string; title: string }; production_plan: { id: string; code: string; title: string; version_id: string; version_no: number; status: string; plan: Record<string, unknown> } | null; profile_bindings: Array<{ capability: string; binding_status: string; profile_version_id: string; profile_code: string; profile_title: string; version_no: number; profile_status: string; contract_hash: string; frozen_job_count: number }>; delivery_targets: Array<{ target_id: string; code: string; title: string; transport: string; target_status: string; version_id: string; version_no: number; version_status: string; spec: Record<string, unknown>; delivery_package_count: number }>; selected_delivery_target_version_id: string | null; impact: { profile_switches_preserve_frozen_jobs: true; profile_frozen_job_counts: Record<string, number>; delivery_package_counts: Record<string, number>; remote_transport_allowed: false }; runtime_contacted: false; network_contacted: false; mutated: false };
export type AdapterContract = { code: string; title: string; kind: string; transport: string; base_url: string | null; executable_ref: string | null; capabilities: string[]; status: string; blockers: string[]; runtime_contacted: false; network_contacted: false; mutated: false };
export type AdapterRegistry = { mode: 'LOCAL_ONLY'; contracts: AdapterContract[]; remote_transport_allowed: false; runtime_contacted: false; network_contacted: false; mutated: false };
export type CapacitySnapshot = { scope: { project_id: string | null }; observed_at: string; jobs_by_state: Record<string, number>; jobs_by_channel: Record<string, number>; queued_count: number; oldest_queued_age_seconds: number | null; active_attempt_count: number; active_worker_count: number; gpu_active_count: number; gpu_concurrency_limit: number; completed_last_24h: number; observation_status: 'OBSERVED_NOT_BENCHMARKED'; webhook_status: 'LOOPBACK_EXPLICIT_BOUNDED'; would_create_jobs: false; runtime_contacted: false; network_contacted: false; mutated: false };
export type OutboxDelivery = { endpoint_url: string; scope: { project_id: string | null }; status: 'DELIVERED' | 'PARTIAL' | 'NO_EVENTS'; delivered_event_ids: number[]; delivered_count: number; failed: Array<Record<string, unknown>>; bounded: true; max_batch_size: number; remote_transport_allowed: false; runtime_contacted: false; network_contacted: false; mutated: boolean };
export type TimelineStatus = { episode: { id: string; code: string; title: string; project_id: string }; timeline: { revision_count: number; latest: Record<string, unknown> | null }; subtitles: { revision_count: number; latest: Record<string, unknown> | null }; audio: { binding_count: number; verified_local_count: number }; renders: { count: number; verified_count: number; latest: Record<string, unknown> | null }; delivery: { count: number; verified_count: number; latest: Record<string, unknown> | null }; observed_at: string; read_only: true; runtime_contacted: false; network_contacted: false; mutated: false };
export type TimelineItemRequest = { track_type?: string; media_version_id?: string | null; start_us: number; end_us: number; parameters?: Record<string, unknown> };
export type TimelineRevision = { id: string; episode_id: string; revision_no: number; status: string; input_snapshot: Record<string, unknown>; items: Array<Record<string, unknown>>; [key: string]: unknown };
export type SubtitleCueRequest = { start_us: number; end_us: number; text: string; style?: Record<string, unknown> };
export type SubtitleAuthorityRequest = { text_authority: 'SCRIPT'; source_document_version_id: string; asr_alignment_media_version_id?: string; asr_profile_version_id?: string };
export type SubtitleRevision = { id: string; episode_id: string; revision_no: number; format: string; content_text: string; input_snapshot: Record<string, unknown>; authority_status: 'VERIFIED_SCRIPT' | 'LEGACY_INCOMPLETE'; cues: Array<Record<string, unknown>>; [key: string]: unknown };
export type AudioBindingRequest = { media_version_id: string; track_type?: string; start_us: number; end_us: number; gain_db?: number; source_license_status?: 'VERIFIED_LOCAL' | 'USER_OWNED' };
export type AudioBinding = { id: string; episode_id: string; media_version_id: string; track_type: string; start_us: number; end_us: number; gain_db: number; source_license_status: string; [key: string]: unknown };
export type EpisodeRender = { id: string; episode_id: string; timeline_revision_id: string; integrity_status: string; [key: string]: unknown };
export type DeliveryPackage = { id: string; episode_render_version_id: string; target_version_id: string; status: string; [key: string]: unknown };
export type TransitionConstraint = { id: string; from_shot_id: string; to_shot_id: string; constraint_type: string; enforcement: string; compatibility_status?: string; [key: string]: unknown };
export type PostProcessRecipe = { id: string; code: string; title: string; steps: Array<Record<string, unknown>>; capability_contract: Record<string, unknown>; [key: string]: unknown };
export type EnhancementRun = { id: string; input_media_version_id: string; recipe_id: string; status: string; [key: string]: unknown };
export type I2VProbePlan = { status: 'READY' | 'BLOCKED'; blockers: string[]; snapshot: { project_id: string; purpose: string; approved_keyframe: { media_version_id: string; shot_id: string; approval_id: string; approved_at: string; sha256: string; byte_size: number } | null; workflow: { id: string; content_hash: string; revision: number } | null; candidate_profile: { id: string; capability: string; status: string; manifest_sha256: string; revision: number } | null; semantic_inputs: Record<string, unknown>; resource_policy: Record<string, unknown> }; plan_hash: string; would_create_job: false; would_contact_comfyui: false; confirmation_required: true };
export type WorkflowVersionSummary = { id: string; workflow_id: string; code: string; title: string; version_no: number; content_hash: string; status: string; contract: Record<string, unknown>; package_rel_path: string | null; published_at: string | null; created_at: string; updated_at: string; revision: number };
export type CanvasNode = { id: string; type: string; shot_id: string; shot_code: string; label: string; state: string; blockers: string[]; take_count: number; variant_count: number; active_job_count: number; thumbnail_media_version_id: string | null; position: { x: number; y: number } | null; variant_lineage: Array<{ id: string; variant_no: number; variant_type: string; parent_variant_id: string | null; status: string; is_stale: boolean; branch_reason: string }>; experiment_progress: Array<{ id: string; title: string; status: string; cell_count: number; expanded_count: number; succeeded_count: number; failed_count: number }>; adjacent_constraints: Array<{ id: string; from_shot_id: string; to_shot_id: string; constraint_type: string; compatibility_status: string; enforcement: string; is_stale: boolean }> };
export type CanvasEdge = { id: string; source: string; target: string; kind: string; status?: string; mutable_by_layout: false };
export type CanvasGraph = { scope: Record<string, unknown>; nodes: CanvasNode[]; edges: CanvasEdge[]; layout: { positions: Record<string, { x: number; y: number }>; groups: Array<Record<string, unknown>>; viewport: Record<string, number>; revision: number; layout_hash: string | null }; page: { cursor: number; limit: number; returned_shots: number; total_shots: number; next_cursor: number | null }; invariants: { layout_changes_business_dependencies: false; max_visible_nodes: number; lazy: true } };

const instanceTokens = new Map<string, string>();

export class ApiRequestError extends Error {
  constructor(
    message: string,
    readonly status: number,
    readonly code: string,
    readonly requestId: string | null,
    readonly retryable: boolean,
    readonly suggestedAction: string | null,
  ) {
    super(message);
    this.name = 'ApiRequestError';
  }
}

async function apiRequestError(response: Response, path: string): Promise<ApiRequestError> {
  let body: { error?: { code?: string; message?: string; request_id?: string | null; retryable?: boolean; suggested_action?: string | null } } = {};
  try {
    body = await response.json() as typeof body;
  } catch {
    // Non-JSON failures still retain the response header request ID.
  }
  const details = body.error;
  const code = details?.code ?? 'HTTP_ERROR';
  const requestId = details?.request_id ?? response.headers?.get?.('X-Request-Id') ?? null;
  const requestSuffix = requestId ? ` · 请求 ID ${requestId}` : '';
  return new ApiRequestError(
    `${details?.message ?? `${path} 请求失败（HTTP ${response.status}）`}${requestSuffix}`,
    response.status,
    code,
    requestId,
    details?.retryable ?? false,
    details?.suggested_action ?? null,
  );
}

async function instanceToken(baseUrl: string): Promise<string> {
  const cached = instanceTokens.get(baseUrl);
  if (cached) return cached;
  const response = await fetch(`${baseUrl}/api/v1/session/bootstrap`);
  if (!response.ok) throw await apiRequestError(response, '/api/v1/session/bootstrap');
  const session = await response.json() as LocalSession;
  instanceTokens.set(baseUrl, session.token);
  return session.token;
}

async function requestJson<T>(path: string, init?: RequestInit, baseUrl = ''): Promise<T> {
  const method = (init?.method ?? 'GET').toUpperCase();
  let securedInit = init;
  if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(method)) {
    const token = await instanceToken(baseUrl);
    const headers = new Headers(init?.headers);
    headers.set('X-Local-Instance-Token', token);
    securedInit = { ...init, headers };
  }
  const response = await fetch(`${baseUrl}${path}`, securedInit);
  if (!response.ok) throw await apiRequestError(response, path);
  const advertisedToken = response.headers?.get?.('X-Local-Instance-Token');
  if (advertisedToken) instanceTokens.set(baseUrl, advertisedToken);
  return response.json() as Promise<T>;
}

export async function bootstrapLocalSession(baseUrl = ''): Promise<LocalSession> {
  const token = await instanceToken(baseUrl);
  return { token, mode: 'LOCAL_ONLY' };
}

export async function healthLive(baseUrl = ''): Promise<HealthCheck> {
  return requestJson<HealthCheck>('/api/v1/health/live', undefined, baseUrl);
}

export async function systemContract(baseUrl = ''): Promise<SystemContract> {
  return requestJson<SystemContract>('/api/v1/system/contract', undefined, baseUrl);
}

export async function listProjects(filters: { search?: string; status?: string } = {}, baseUrl = ''): Promise<{ items: Project[] }> {
  const query = new URLSearchParams();
  if (filters.search) query.set('search', filters.search);
  if (filters.status) query.set('status', filters.status);
  const suffix = query.size ? `?${query.toString()}` : '';
  return requestJson<{ items: Project[] }>(`/api/v1/projects${suffix}`, undefined, baseUrl);
}

export async function planProjectCreation(payload: ProjectCreatePayload, baseUrl = ''): Promise<{ plan: ProjectCreationPlan }> {
  return requestJson('/api/v1/projects:plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createProject(payload: ProjectCreatePayload, baseUrl = ''): Promise<{ project: Project; blockers: string[] }> {
  return requestJson('/api/v1/projects', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function copyProjectTemplate(projectId: string, payload: { code: string; title: string }, baseUrl = ''): Promise<{ project: Project; copy_report: { source_project_id: string; copied: Record<string, number>; excluded: string[] } }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}:copy-template`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function exportProjectPackage(projectId: string, baseUrl = ''): Promise<{ package: ProjectPackageExport }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/packages:export`, { method: 'POST' }, baseUrl);
}

export async function dryRunProjectPackage(projectId: string, relPath: string, baseUrl = ''): Promise<{ dry_run: ProjectPackageDryRun }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/packages:dry-run`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rel_path: relPath }) }, baseUrl);
}

export async function stageProjectPackage(inboxName: string, baseUrl = ''): Promise<{ staging: ProjectPackageStaging }> {
  return requestJson('/api/v1/project-packages:stage', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ inbox_name: inboxName }) }, baseUrl);
}

export async function dryRunStagedProjectPackage(stageToken: string, baseUrl = ''): Promise<{ dry_run: ProjectPackageDryRun }> {
  return requestJson(`/api/v1/project-packages/${encodeURIComponent(stageToken)}:dry-run`, { method: 'POST' }, baseUrl);
}

export async function commitStagedProjectPackage(stageToken: string, payload: { identity_mode: 'REBIND_EXISTING' | 'IMPORT_AS_COPY_REWRITE_IDENTITY'; code?: string; title?: string }, baseUrl = ''): Promise<{ commit: ProjectPackageCommit }> {
  return requestJson(`/api/v1/project-packages/${encodeURIComponent(stageToken)}:commit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listProfiles(baseUrl = ''): Promise<{ items: Profile[] }> {
  return requestJson<{ items: Profile[] }>('/api/v1/profiles', undefined, baseUrl);
}

export async function getProfileVersion(profileVersionId: string, baseUrl = ''): Promise<{ profile_version: ProfileVersionDetail }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}`, undefined, baseUrl);
}

export async function deriveProfileContractVersion(profileVersionId: string, payload: { expected_source_revision: number; input_contract: Record<string, unknown>; parameter_schema: Record<string, unknown>; output_contract: Record<string, unknown>; resource_policy: Record<string, unknown> }, baseUrl = ''): Promise<{ profile_version: ProfileVersionDetail }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}:derive-contract`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function validateProfileContractVersion(profileVersionId: string, baseUrl = ''): Promise<{ validation: ProfileValidation }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}:validate-contract`, { method: 'POST' }, baseUrl);
}

export async function publishProfileContractVersion(profileVersionId: string, baseUrl = ''): Promise<{ profile_version: ProfileVersionDetail }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}:publish-contract`, { method: 'POST' }, baseUrl);
}

export async function latestDiagnostics(baseUrl = ''): Promise<{ run: DiagnosticRun | null }> {
  return requestJson<{ run: DiagnosticRun | null }>('/api/v1/diagnostics/latest', undefined, baseUrl);
}

export async function runDiagnostics(baseUrl = ''): Promise<{ run: DiagnosticRun }> {
  return requestJson<{ run: DiagnosticRun }>('/api/v1/diagnostics/runs', { method: 'POST' }, baseUrl);
}

export async function listReviewTemplates(baseUrl = ''): Promise<{ items: ReviewTemplate[] }> {
  return requestJson<{ items: ReviewTemplate[] }>('/api/v1/review-templates', undefined, baseUrl);
}

export async function reviewInbox(projectId?: string, baseUrl = ''): Promise<{ items: ReviewInboxItem[] }> {
  const query = projectId ? `?project_id=${encodeURIComponent(projectId)}` : '';
  return requestJson<{ items: ReviewInboxItem[] }>(`/api/v1/reviews/inbox${query}`, undefined, baseUrl);
}

export async function getReviewContext(mediaVersionId: string, baseUrl = ''): Promise<{ media_version: Record<string, unknown>; subject_revision: number; template: ReviewTemplate; selections: Array<Record<string, unknown>>; reviews: Array<Record<string, unknown>>; machine_checks: Array<Record<string, unknown>> }> {
  return requestJson(`/api/v1/subjects/MEDIA_VERSION/${encodeURIComponent(mediaVersionId)}/review-context`, undefined, baseUrl);
}

export async function runMachineCheck(mediaVersionId: string, baseUrl = ''): Promise<{ machine_check: Record<string, unknown> }> {
  return requestJson(`/api/v1/subjects/MEDIA_VERSION/${encodeURIComponent(mediaVersionId)}/machine-checks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ policy_version: 'g8_audio_qc_v1' }) }, baseUrl);
}

export async function submitReview(mediaVersionId: string, payload: { template_version_id: string; decision: 'APPROVED' | 'REJECTED' | 'NEEDS_CHANGES'; expected_subject_revision: number; checks: Array<{ item_id: string; result: 'PASS' | 'FAIL'; comment?: string }>; comment?: string }, baseUrl = ''): Promise<{ review: Record<string, unknown> }> {
  return requestJson(`/api/v1/subjects/MEDIA_VERSION/${encodeURIComponent(mediaVersionId)}/reviews`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listVideoAnnotations(mediaVersionId: string, baseUrl = ''): Promise<{ items: VideoAnnotation[] }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}/annotations`, undefined, baseUrl);
}

export async function createVideoAnnotation(mediaVersionId: string, payload: { timecode_ms: number; category: string; comment: string; snapshot_media_version_id?: string; rework_job_id?: string }, baseUrl = ''): Promise<{ annotation: VideoAnnotation }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}/annotations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function selectMediaVersion(mediaVersionId: string, selectionType: string, baseUrl = ''): Promise<{ selection: Record<string, unknown> }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}:select`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ selection_type: selectionType }) }, baseUrl);
}

export async function exportEpisodeContactSheet(episodeId: string, baseUrl = ''): Promise<{ export: ContactSheetExport }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/contact-sheet:export`, { method: 'POST' }, baseUrl);
}

export async function createFrameAnchor(mediaVersionId: string, payload: { source_time_us?: number; source_frame_index?: number; position_mode?: 'FIRST_FRAME' | 'LAST_FRAME'; role_hint: 'FIRST_FRAME' | 'CURRENT_FRAME' | 'LAST_FRAME' }, baseUrl = ''): Promise<{ frame_anchor: FrameAnchor }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}:create-frame-anchor`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createKeyframeCandidate(mediaVersionId: string, shotId: string, baseUrl = ''): Promise<{ media: KeyframeCandidate }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}:create-keyframe-candidate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ shot_id: shotId }) }, baseUrl);
}

export async function listJobs(projectId?: string, baseUrl = ''): Promise<{ items: Job[] }> {
  const query = projectId ? `?project_id=${encodeURIComponent(projectId)}` : '';
  return requestJson<{ items: Job[] }>(`/api/v1/jobs${query}`, undefined, baseUrl);
}

export async function createGenerationIntent(payload: { project_id: string; owner_type: string; owner_id: string; purpose: string; creative_goal: string }, baseUrl = ''): Promise<{ intent: GenerationIntent }> {
  return requestJson('/api/v1/generation-intents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listGenerationIntents(projectId?: string, baseUrl = ''): Promise<{ items: GenerationIntent[] }> {
  const query = projectId ? `?project_id=${encodeURIComponent(projectId)}` : '';
  return requestJson(`/api/v1/generation-intents${query}`, undefined, baseUrl);
}

export async function getGenerationIntent(intentId: string, baseUrl = ''): Promise<{ intent: GenerationIntent }> {
  return requestJson(`/api/v1/generation-intents/${encodeURIComponent(intentId)}`, undefined, baseUrl);
}

export async function planGenerationVariant(payload: GenerationVariantDraft, baseUrl = ''): Promise<{ plan: GenerationVariantPlan }> {
  return requestJson('/api/v1/generation-variants:plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createGenerationVariant(payload: GenerationVariantDraft & { plan_hash: string }, baseUrl = ''): Promise<{ variant: GenerationVariant }> {
  return requestJson('/api/v1/generation-variants', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listGenerationVariants(intentId: string, baseUrl = ''): Promise<{ items: GenerationVariant[] }> {
  return requestJson(`/api/v1/generation-intents/${encodeURIComponent(intentId)}/variants`, undefined, baseUrl);
}

export async function getGenerationVariant(variantId: string, baseUrl = ''): Promise<{ variant: GenerationVariant }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}`, undefined, baseUrl);
}

export async function getGenerationVariantLineage(variantId: string, baseUrl = ''): Promise<{ items: GenerationVariant[] }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}/lineage`, undefined, baseUrl);
}

export async function deriveGenerationVariantPlan(variantId: string, payload: { operation: 'RESAMPLE_NEW_SEED' | 'RESUBMIT_PROVIDER_RANDOM' | 'EXACT_REPLAY' | 'PROMPT_BRANCH' | 'SOURCE_IMAGE_BRANCH' | 'PROFILE_BRANCH'; explicit_seed?: number; prompt_revision_id?: string; first_frame_media_version_id?: string; profile_version_id?: string; branch_reason: string }, baseUrl = ''): Promise<{ plan: GenerationVariantPlan & { draft: GenerationVariantDraft; diff: Record<string, unknown>; reproducibility: Record<string, unknown> } }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}:derive-plan`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function deriveGenerationVariantSeedBatch(variantId: string, payload: { seeds: number[]; branch_reason: string }, baseUrl = ''): Promise<{ batch: { parent_variant_id: string; count: number; plans: Array<GenerationVariantPlan & { draft: GenerationVariantDraft; diff: Record<string, unknown> }>; would_persist_variants: false; would_create_jobs: false } }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}:derive-seed-batch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createPrompt(payload: { project_id: string; owner_type: string; owner_id: string; purpose: string; title: string; content_text: string; structured?: Record<string, unknown> }, baseUrl = ''): Promise<{ prompt: Record<string, unknown>; revision: PromptRevision }> {
  return requestJson('/api/v1/prompts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listPrompts(projectId: string, ownerType?: string, ownerId?: string, baseUrl = ''): Promise<{ items: Array<Record<string, unknown>> }> {
  const query = new URLSearchParams({ project_id: projectId });
  if (ownerType) query.set('owner_type', ownerType);
  if (ownerId) query.set('owner_id', ownerId);
  return requestJson(`/api/v1/prompts?${query.toString()}`, undefined, baseUrl);
}

export async function listScriptBreakdownDrafts(projectId: string, baseUrl = ''): Promise<{ items: ScriptBreakdownDraft[]; automatic_apply: false; requires_human_action: true }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/script-breakdown-drafts`, undefined, baseUrl);
}

export async function branchPromptRevision(revisionId: string, payload: { content_text: string; structured?: Record<string, unknown> }, baseUrl = ''): Promise<{ revision: PromptRevision }> {
  return requestJson(`/api/v1/prompt-revisions/${encodeURIComponent(revisionId)}:branch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function getPromptRevision(revisionId: string, baseUrl = ''): Promise<{ revision: PromptRevision }> {
  return requestJson(`/api/v1/prompt-revisions/${encodeURIComponent(revisionId)}`, undefined, baseUrl);
}

export async function validateShotTransitionConstraint(constraintId: string, baseUrl = ''): Promise<{ validation: { constraint_id: string; status: 'COMPATIBLE' | 'WARNING' | 'BLOCKED'; blockers: Array<Record<string, unknown>>; warnings: Array<Record<string, unknown>> } }> {
  return requestJson(`/api/v1/shot-transitions/${encodeURIComponent(constraintId)}:validate`, { method: 'POST' }, baseUrl);
}

export async function createGenerationExperiment(payload: { intent_id: string; title: string; axes: Record<string, unknown[]>; max_parallel?: number; resource_estimate?: Record<string, unknown> }, baseUrl = ''): Promise<{ experiment: GenerationExperiment }> {
  return requestJson('/api/v1/generation-experiments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function estimateGenerationExperiment(experimentId: string, baseUrl = ''): Promise<{ estimate: GenerationExperimentEstimate }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}/estimate`, undefined, baseUrl);
}

export async function confirmGenerationExperiment(experimentId: string, payload: { plan_hash: string; limit?: number; confirm_large_matrix?: boolean }, baseUrl = ''): Promise<{ result: Record<string, unknown> }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}:confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function expandGenerationExperiment(experimentId: string, limit = 20, baseUrl = ''): Promise<{ result: Record<string, unknown> }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}:expand`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ limit }) }, baseUrl);
}

export async function cancelRemainingGenerationExperiment(experimentId: string, baseUrl = ''): Promise<{ result: { experiment_id: string; status: 'CANCELLED'; cancelled: Array<Record<string, string>>; preserved: Array<Record<string, string>>; unexpanded_cancelled_count: number } }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}:cancel-remaining`, { method: 'POST' }, baseUrl);
}

export async function listSeasons(projectId: string, baseUrl = ''): Promise<{ items: Array<{ id: string; code: string; title: string }> }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/seasons`, undefined, baseUrl);
}

export async function listEpisodes(seasonId: string, baseUrl = ''): Promise<{ items: Array<{ id: string; code: string; title: string; production_status: string }> }> {
  return requestJson(`/api/v1/projects/seasons/${encodeURIComponent(seasonId)}/episodes`, undefined, baseUrl);
}

export async function listProjectScenes(projectId: string, baseUrl = ''): Promise<{ items: MasterScene[] }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/scenes`, undefined, baseUrl);
}

export async function createProjectScene(projectId: string, payload: { code: string; title: string; location?: string; time_of_day?: string }, baseUrl = ''): Promise<{ scene: MasterScene }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/scenes`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listEpisodeSceneRanges(episodeId: string, baseUrl = ''): Promise<{ items: EpisodeSceneRange[] }> {
  return requestJson(`/api/v1/projects/episodes/${encodeURIComponent(episodeId)}/scene-ranges`, undefined, baseUrl);
}

export async function bindEpisodeSceneRange(episodeId: string, payload: { scene_id: string; ordinal: number; source_start: number; source_end: number; source_label?: string }, baseUrl = ''): Promise<{ range: EpisodeSceneRange }> {
  return requestJson(`/api/v1/projects/episodes/${encodeURIComponent(episodeId)}/scene-ranges`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function getEpisodeProduction(episodeId: string, baseUrl = ''): Promise<{ episode: Record<string, unknown>; items: Array<Record<string, unknown>> }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/production`, undefined, baseUrl);
}

export async function listCreativeEntries(projectId: string, kind?: string, baseUrl = ''): Promise<{ items: CreativeEntry[] }> {
  const query = new URLSearchParams({ project_id: projectId });
  if (kind) query.set('kind', kind);
  return requestJson(`/api/v1/creative-entries?${query.toString()}`, undefined, baseUrl);
}

export async function getCreativeEntry(entryId: string, baseUrl = ''): Promise<{ entry: CreativeEntry; revisions: CreativeEntryRevision[] }> {
  return requestJson(`/api/v1/creative-entries/${encodeURIComponent(entryId)}`, undefined, baseUrl);
}

export async function createCreativeEntry(payload: { project_id: string; kind: string; code: string; title: string; content: Record<string, unknown>; change_note: string }, baseUrl = ''): Promise<{ entry: CreativeEntry }> {
  return requestJson('/api/v1/creative-entries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createCreativeEntryRevision(entryId: string, payload: { content: Record<string, unknown>; change_note: string }, baseUrl = ''): Promise<{ revision: CreativeEntryRevision }> {
  return requestJson(`/api/v1/creative-entries/${encodeURIComponent(entryId)}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function compareCreativeEntryRevisions(entryId: string, leftRevisionId: string, rightRevisionId: string, baseUrl = ''): Promise<{ comparison: { entry_id: string; left: CreativeEntryRevision; right: CreativeEntryRevision; changes: Array<{ field: string; before: unknown; after: unknown }>; read_only: true } }> {
  const query = new URLSearchParams({ left_revision_id: leftRevisionId, right_revision_id: rightRevisionId });
  return requestJson(`/api/v1/creative-entries/${encodeURIComponent(entryId)}/compare?${query.toString()}`, undefined, baseUrl);
}

export async function restoreCreativeEntryRevision(entryId: string, revisionId: string, changeNote: string, baseUrl = ''): Promise<{ revision: CreativeEntryRevision }> {
  return requestJson(`/api/v1/creative-entries/${encodeURIComponent(entryId)}:restore`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ revision_id: revisionId, change_note: changeNote }) }, baseUrl);
}

export async function getShotContinuityContext(shotId: string, baseUrl = ''): Promise<{ continuity: ContinuityContext }> {
  return requestJson(`/api/v1/shots/${encodeURIComponent(shotId)}/continuity-context`, undefined, baseUrl);
}

export async function createShotRevision(shotId: string, fields: Record<string, unknown>, freeze: boolean, baseUrl = ''): Promise<{ shot_revision: Record<string, unknown> }> {
  return requestJson(`/api/v1/projects/shots/${encodeURIComponent(shotId)}/revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fields, freeze }) }, baseUrl);
}

export async function markShotProductionReady(shotId: string, baseUrl = ''): Promise<{ shot: Record<string, unknown> }> {
  return requestJson(`/api/v1/projects/shots/${encodeURIComponent(shotId)}:mark-production-ready`, { method: 'POST' }, baseUrl);
}

export async function getEpisodeTimelineStatus(episodeId: string, baseUrl = ''): Promise<{ status: TimelineStatus }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/timeline-status`, undefined, baseUrl);
}

export async function createTimelineRevision(episodeId: string, payload: { items: TimelineItemRequest[]; input_snapshot?: Record<string, unknown>; status?: string }, baseUrl = ''): Promise<{ timeline: TimelineRevision }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/timeline-revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function getTimelineRevision(timelineRevisionId: string, baseUrl = ''): Promise<{ timeline: TimelineRevision }> {
  return requestJson(`/api/v1/timeline-revisions/${encodeURIComponent(timelineRevisionId)}`, undefined, baseUrl);
}

export async function exportTimelineRevision(timelineRevisionId: string, baseUrl = ''): Promise<{ export: TimelineExport }> {
  return requestJson(`/api/v1/timeline-revisions/${encodeURIComponent(timelineRevisionId)}:export`, { method: 'POST' }, baseUrl);
}

export async function createSubtitleRevision(episodeId: string, payload: { cues: SubtitleCueRequest[]; authority: SubtitleAuthorityRequest; format?: string }, baseUrl = ''): Promise<{ subtitle: SubtitleRevision }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/subtitle-revisions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function getSubtitleRevision(subtitleRevisionId: string, baseUrl = ''): Promise<{ subtitle: SubtitleRevision }> {
  return requestJson(`/api/v1/subtitle-revisions/${encodeURIComponent(subtitleRevisionId)}`, undefined, baseUrl);
}

export async function bindEpisodeAudio(episodeId: string, payload: AudioBindingRequest, baseUrl = ''): Promise<{ audio_binding: AudioBinding }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/audio-bindings`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listEpisodeAudioBindings(episodeId: string, baseUrl = ''): Promise<{ items: AudioBinding[] }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/audio-bindings`, undefined, baseUrl);
}

export async function renderEpisode(timelineRevisionId: string, baseUrl = ''): Promise<{ render: EpisodeRender }> {
  return requestJson(`/api/v1/timeline-revisions/${encodeURIComponent(timelineRevisionId)}:render`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ timeline_revision_id: timelineRevisionId }) }, baseUrl);
}

export async function buildDeliveryPackage(payload: { episode_render_version_id: string; target_version_id: string }, baseUrl = ''): Promise<{ delivery: DeliveryPackage }> {
  return requestJson('/api/v1/delivery-packages', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function verifyDeliveryPackage(packageId: string, baseUrl = ''): Promise<{ delivery: DeliveryPackage }> {
  return requestJson(`/api/v1/delivery-packages/${encodeURIComponent(packageId)}:verify`, undefined, baseUrl);
}

export async function withdrawDeliveryPackage(packageId: string, reason: string, baseUrl = ''): Promise<{ delivery: DeliveryPackage }> {
  return requestJson(`/api/v1/delivery-packages/${encodeURIComponent(packageId)}:withdraw`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reason }) }, baseUrl);
}

export async function getFrameAnchor(anchorId: string, baseUrl = ''): Promise<{ frame_anchor: FrameAnchor }> {
  return requestJson(`/api/v1/frame-anchors/${encodeURIComponent(anchorId)}`, undefined, baseUrl);
}

export async function createShotTransitionConstraint(payload: { from_shot_id: string; to_shot_id: string; constraint_type: string; from_anchor_id?: string; to_anchor_id?: string; enforcement?: string; note?: string }, baseUrl = ''): Promise<{ constraint: TransitionConstraint }> {
  return requestJson('/api/v1/shot-transitions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createPostProcessRecipe(payload: { code: string; title: string; steps: Array<Record<string, unknown>>; capability_contract?: Record<string, unknown> }, baseUrl = ''): Promise<{ recipe: PostProcessRecipe }> {
  return requestJson('/api/v1/post-process-recipes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function getPostProcessRecipe(recipeId: string, baseUrl = ''): Promise<{ recipe: PostProcessRecipe }> {
  return requestJson(`/api/v1/post-process-recipes/${encodeURIComponent(recipeId)}`, undefined, baseUrl);
}

export async function runEnhancement(payload: { input_media_version_id: string; recipe_id: string; parameters?: Record<string, unknown> }, baseUrl = ''): Promise<{ enhancement: EnhancementRun }> {
  return requestJson('/api/v1/enhancement-runs', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function getG8Readiness(projectId: string, episodeId?: string, baseUrl = ''): Promise<{ readiness: G8Readiness }> {
  const query = episodeId ? `?episode_id=${encodeURIComponent(episodeId)}` : '';
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g8${query}`, undefined, baseUrl);
}

export async function getG9Readiness(projectId: string, episodeId?: string, baseUrl = ''): Promise<{ readiness: G9Readiness }> {
  const query = episodeId ? `?episode_id=${encodeURIComponent(episodeId)}` : '';
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g9${query}`, undefined, baseUrl);
}

export async function localLLMStatus(baseUrl = ''): Promise<{ status: LocalLLMStatus }> {
  return requestJson('/api/v1/local-llm/status', undefined, baseUrl);
}

export async function h3CandidateRuntime(baseUrl = ''): Promise<{ runtime: H3Runtime; candidate_assets: Record<string, string> }> {
  return requestJson('/api/v1/h3/candidate-runtime', undefined, baseUrl);
}

export async function getG6Readiness(projectId: string, baseUrl = ''): Promise<{ readiness: G6Readiness }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g6`, undefined, baseUrl);
}

export async function planG6I2VProbe(projectId: string, baseUrl = ''): Promise<{ plan: I2VProbePlan }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g6/i2v-probe-plan`, undefined, baseUrl);
}

export async function getG7Readiness(projectId: string, baseUrl = ''): Promise<{ readiness: G7Readiness }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g7`, undefined, baseUrl);
}

export async function getProjectConfiguration(projectId: string, baseUrl = ''): Promise<{ configuration: ProjectConfiguration }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/configuration`, undefined, baseUrl);
}

export async function getModelCompatibility(projectId: string, baseUrl = ''): Promise<{ compatibility: ModelCompatibilitySnapshot }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/model-compatibility`, undefined, baseUrl);
}

export async function getAdapterContracts(baseUrl = ''): Promise<{ registry: AdapterRegistry }> {
  return requestJson('/api/v1/adapters/contracts', undefined, baseUrl);
}

export async function getCapacitySnapshot(projectId?: string, baseUrl = ''): Promise<{ snapshot: CapacitySnapshot }> {
  const query = projectId ? `?project_id=${encodeURIComponent(projectId)}` : '';
  return requestJson(`/api/v1/capacity/snapshot${query}`, undefined, baseUrl);
}

export async function deliverOutboxEvents(payload: { endpoint_url: string; project_id?: string; after_event_id?: number; limit?: number }, baseUrl = ''): Promise<{ delivery: OutboxDelivery }> {
  return requestJson('/api/v1/events:deliver', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function runG7NetworkE2E(projectId: string, baseUrl = ''): Promise<{ attestation: Record<string, unknown> }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g7/network-e2e`, { method: 'POST' }, baseUrl);
}

export async function authorizeWorkspaceAsset(projectId: string, mediaVersionId: string, baseUrl = ''): Promise<{ authorization: Record<string, unknown> }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/workspace-assets/authorize`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ media_version_id: mediaVersionId }) }, baseUrl);
}

export async function createBrandKit(projectId: string, payload: { code: string; title: string; tokens: Record<string, unknown> }, baseUrl = ''): Promise<{ brand_kit: Record<string, unknown> }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/brand-kits`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createModelCompatibilityReport(projectId: string, modelArtifactId: string, baseUrl = ''): Promise<{ report: ModelCompatibilityReport }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/model-compatibility-report`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model_artifact_id: modelArtifactId }) }, baseUrl);
}

export async function importModelLicenseEvidence(projectId: string, payload: { model_artifact_id: string; evidence_path: string; license_name: string; license_status: 'LOCAL_LICENSE_VERIFIED' | 'USER_OWNED' }, baseUrl = ''): Promise<{ evidence: Record<string, unknown>; report: ModelCompatibilityReport }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/model-license-evidence`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listWorkflowVersions(baseUrl = ''): Promise<{ items: WorkflowVersionSummary[]; runtime_contacted: false }> {
  return requestJson('/api/v1/workflow-versions', undefined, baseUrl);
}

export async function getProductionCanvas(scopeType: 'EPISODE' | 'SHOT', scopeId: string, cursor = 0, limit = 100, baseUrl = ''): Promise<{ graph: CanvasGraph }> {
  return requestJson(`/api/v1/canvas/${scopeType}/${encodeURIComponent(scopeId)}?cursor=${cursor}&limit=${limit}`, undefined, baseUrl);
}

export async function saveProductionCanvasLayout(scopeType: 'EPISODE' | 'SHOT', scopeId: string, payload: { expected_revision?: number; positions: Record<string, { x: number; y: number }>; groups?: Array<Record<string, unknown>>; viewport?: Record<string, number> }, baseUrl = ''): Promise<{ layout: CanvasGraph['layout'] }> {
  return requestJson(`/api/v1/canvas/${scopeType}/${encodeURIComponent(scopeId)}/layout`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function preflightProductionCanvasRun(scopeType: 'EPISODE' | 'SHOT', scopeId: string, payload: { mode: 'NODE' | 'FROM' | 'TO' | 'RANGE'; from_node_id?: string; to_node_id?: string; max_nodes?: number }, baseUrl = ''): Promise<{ plan: { id: string; status: string; node_ids: string[]; blockers: Array<Record<string, unknown>>; estimate: Record<string, unknown>; submitted: false } }> {
  return requestJson(`/api/v1/canvas/${scopeType}/${encodeURIComponent(scopeId)}/runs:preflight`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}
"""
    client_path.write_text(client_source, encoding="utf-8")
    print(f"wrote {openapi_path}")
    print(f"wrote {client_path}")


if __name__ == "__main__":
    main()
