"""Generate the committed OpenAPI snapshot and a small typed TS client from the app."""

from __future__ import annotations

import json
import sys
from importlib import import_module
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "apps" / "api"
sys.path.insert(0, str(API_ROOT))

app = import_module("local_drama.main").app


def main() -> None:
    spec = app.openapi()
    openapi_path = ROOT / "docs" / "openapi" / "openapi.json"
    openapi_path.write_text(
        json.dumps(spec, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    client_path = ROOT / "apps" / "web" / "src" / "generated" / "api.ts"
    client_source = """/* Generated by scripts/generate_client.py; do not edit manually. */
export type HealthCheck = { status: string; checks: Record<string, string> };
export type SystemContract = Record<string, string>;
export type Project = { id: string; code: string; title: string; status: string; revision: number; [key: string]: unknown };
export type Profile = { id: string; code: string; title: string; version_id: string; capability: string; status: string; [key: string]: unknown };
export type ProfileContract = { input_contract: Record<string, unknown>; parameter_schema: Record<string, unknown>; output_contract: Record<string, unknown>; resource_policy: Record<string, unknown> };
export type ProfileValidation = { id: string; profile_version_id?: string; contract_hash: string; status: 'PASS' | 'FAIL'; checks: Array<{ code: string; passed: boolean; label?: string }>; runtime_contacted?: false; network_contacted?: false };
export type ProfileVersionDetail = { id: string; execution_profile_id: string; code: string; title: string; version_no: number; capability: string; status: string; revision: number; input_contract: Record<string, unknown>; parameter_schema: Record<string, unknown>; output_contract: Record<string, unknown>; resource_policy: Record<string, unknown>; capability_contract?: Record<string, unknown>; contract_hash: string; validation: ProfileValidation | null };
export type DiagnosticRun = { id: string; status: string; checks: Array<{ code: string; category: string; status: string; observed: Record<string, unknown> }> };
export type ReviewTemplate = { id: string; code: string; version_no: number; subject_type: string; items: Array<{ id: string; label: string; required: boolean }> };
export type ReviewInboxItem = { media_version_id: string; media_asset_id: string; project_id: string; media_kind: string; stage: string; decision: string | null; is_stale: number | null; [key: string]: unknown };
export type FrameAnchor = { id: string; source_media_version_id: string; source_time_us: number; source_frame_index: number; extracted_media_version_id: string; role_hint: string; sha256: string; requested_time_us: number | null; resolved_time_us: number; source_sha256: string; extraction_method: string; [key: string]: unknown };
export type KeyframeCandidate = { id: string; media_asset_id: string; project_id: string; owner_type: 'SHOT'; owner_id: string; media_kind: 'IMAGE'; stage: 'KEYFRAME'; parent_version_id: string; duplicate: boolean; [key: string]: unknown };
export type Job = { id: string; type: string; project_id: string; state: string; channel: string; priority: number; max_attempts: number; revision: number; [key: string]: unknown };
export type GenerationIntent = { id: string; project_id: string; owner_type: string; owner_id: string; purpose: string; creative_goal: string; [key: string]: unknown };
export type VariantInput = { role: string; media_version_id: string; ordinal?: number };
export type GenerationVariantDraft = { intent_id: string; variant_type: string; parent_variant_id?: string | null; branch_reason: string; prompt_revision_id?: string | null; profile_version_id: string; parameter_set?: Record<string, unknown>; seed_policy: string; explicit_seed?: number | null; provider_random_nonce?: string | null; bindings?: VariantInput[] };
export type GenerationVariant = { id: string; intent_id: string; variant_no: number; variant_type: string; parent_variant_id: string | null; recipe_hash: string; status: string; bindings: Array<Record<string, unknown>>; [key: string]: unknown };
export type GenerationVariantPlan = { intent_id: string; status: 'READY'; plan_hash: string; recipe_hash: string; dependencies: Record<string, unknown>; would_persist_variant: false; would_create_job: false };
export type PromptRevision = { id: string; prompt_id: string; revision_no: number; parent_revision_id: string | null; content_text: string; structured: Record<string, unknown>; content_hash: string; status: 'FROZEN'; [key: string]: unknown };
export type GenerationExperiment = { id: string; intent_id: string; title: string; status: 'DRAFT' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED'; plan_hash: string; cell_count: number; expanded_count: number; remaining_count: number; [key: string]: unknown };
export type GenerationExperimentEstimate = { experiment_id: string; cell_count: number; expanded_count: number; remaining_count: number; max_parallel: number; estimated_cpu_seconds: number; estimated_disk_bytes: number; gpu_slots: number; status: string; plan_hash: string; confirmation_required: boolean; large_matrix_confirmation_required: boolean; large_matrix_confirmation_threshold: number; would_create_jobs: false };
export type LocalLLMStatus = { status: string; base_url: string; model: string | null; error_code?: string; available_models?: string[]; model_present?: boolean };
export type H3Runtime = { status: string; release_root?: string; missing_sidecars?: string[]; missing_model_files?: string[]; required_sidecars?: string[] };
export type G6Readiness = { gate: 'G6'; status: 'PASS' | 'IN_PROGRESS'; project_id: string; checks: Array<{ code: string; passed: boolean; count?: number }>; next_required_action: string | null; evidence: Record<string, unknown>; mutated: false };
export type I2VProbePlan = { status: 'READY' | 'BLOCKED'; blockers: string[]; snapshot: { project_id: string; purpose: string; approved_keyframe: { media_version_id: string; shot_id: string; approval_id: string; approved_at: string; sha256: string; byte_size: number } | null; workflow: { id: string; content_hash: string; revision: number } | null; candidate_profile: { id: string; capability: string; status: string; manifest_sha256: string; revision: number } | null; semantic_inputs: Record<string, unknown>; resource_policy: Record<string, unknown> }; plan_hash: string; would_create_job: false; would_contact_comfyui: false; confirmation_required: true };
export type WorkflowVersionSummary = { id: string; workflow_id: string; code: string; title: string; version_no: number; content_hash: string; status: string; contract: Record<string, unknown>; package_rel_path: string | null; published_at: string | null; created_at: string; updated_at: string; revision: number };
export type CanvasNode = { id: string; type: string; shot_id: string; shot_code: string; label: string; state: string; blockers: string[]; take_count: number; variant_count: number; active_job_count: number; thumbnail_media_version_id: string | null; position: { x: number; y: number } | null };
export type CanvasEdge = { id: string; source: string; target: string; kind: string; status?: string; mutable_by_layout: false };
export type CanvasGraph = { scope: Record<string, unknown>; nodes: CanvasNode[]; edges: CanvasEdge[]; layout: { positions: Record<string, { x: number; y: number }>; groups: Array<Record<string, unknown>>; viewport: Record<string, number>; revision: number; layout_hash: string | null }; page: { cursor: number; limit: number; returned_shots: number; total_shots: number; next_cursor: number | null }; invariants: { layout_changes_business_dependencies: false; max_visible_nodes: number; lazy: true } };

async function requestJson<T>(path: string, init?: RequestInit, baseUrl = ''): Promise<T> {
  const response = await fetch(`${baseUrl}${path}`, init);
  if (!response.ok) throw new Error(`${path} failed: ${response.status}`);
  return response.json() as Promise<T>;
}

export async function healthLive(baseUrl = ''): Promise<HealthCheck> {
  return requestJson<HealthCheck>('/api/v1/health/live', undefined, baseUrl);
}

export async function systemContract(baseUrl = ''): Promise<SystemContract> {
  return requestJson<SystemContract>('/api/v1/system/contract', undefined, baseUrl);
}

export async function listProjects(baseUrl = ''): Promise<{ items: Project[] }> {
  return requestJson<{ items: Project[] }>('/api/v1/projects', undefined, baseUrl);
}

export async function listProfiles(baseUrl = ''): Promise<{ items: Profile[] }> {
  return requestJson<{ items: Profile[] }>('/api/v1/profiles', undefined, baseUrl);
}

export async function getProfileVersion(profileVersionId: string, baseUrl = ''): Promise<{ profile_version: ProfileVersionDetail }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}`, undefined, baseUrl);
}

export async function deriveProfileContractVersion(profileVersionId: string, payload: { expected_source_revision: number; input_contract: Record<string, unknown>; parameter_schema: Record<string, unknown>; output_contract: Record<string, unknown>; resource_policy: Record<string, unknown> }, baseUrl = ''): Promise<{ profile_version: ProfileVersionDetail }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}:derive-contract`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function validateProfileContractVersion(profileVersionId: string, baseUrl = ''): Promise<{ validation: ProfileValidation }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}:validate-contract`, { method: 'POST' }, baseUrl);
}

export async function publishProfileContractVersion(profileVersionId: string, baseUrl = ''): Promise<{ profile_version: ProfileVersionDetail }> {
  return requestJson(`/api/v1/profile-versions/${encodeURIComponent(profileVersionId)}:publish-contract`, { method: 'POST' }, baseUrl);
}

export async function latestDiagnostics(baseUrl = ''): Promise<{ run: DiagnosticRun | null }> {
  return requestJson<{ run: DiagnosticRun | null }>('/api/v1/diagnostics/latest', undefined, baseUrl);
}

export async function runDiagnostics(baseUrl = ''): Promise<{ run: DiagnosticRun }> {
  return requestJson<{ run: DiagnosticRun }>('/api/v1/diagnostics/runs', { method: 'POST' }, baseUrl);
}

export async function listReviewTemplates(baseUrl = ''): Promise<{ items: ReviewTemplate[] }> {
  return requestJson<{ items: ReviewTemplate[] }>('/api/v1/review-templates', undefined, baseUrl);
}

export async function reviewInbox(projectId?: string, baseUrl = ''): Promise<{ items: ReviewInboxItem[] }> {
  const query = projectId ? `?project_id=${encodeURIComponent(projectId)}` : '';
  return requestJson<{ items: ReviewInboxItem[] }>(`/api/v1/reviews/inbox${query}`, undefined, baseUrl);
}

export async function getReviewContext(mediaVersionId: string, baseUrl = ''): Promise<{ media_version: Record<string, unknown>; subject_revision: number; template: ReviewTemplate; selections: Array<Record<string, unknown>>; reviews: Array<Record<string, unknown>>; machine_checks: Array<Record<string, unknown>> }> {
  return requestJson(`/api/v1/subjects/MEDIA_VERSION/${encodeURIComponent(mediaVersionId)}/review-context`, undefined, baseUrl);
}

export async function submitReview(mediaVersionId: string, payload: { template_version_id: string; decision: 'APPROVED' | 'REJECTED' | 'NEEDS_CHANGES'; expected_subject_revision: number; checks: Array<{ item_id: string; result: 'PASS' | 'FAIL'; comment?: string }>; comment?: string }, baseUrl = ''): Promise<{ review: Record<string, unknown> }> {
  return requestJson(`/api/v1/subjects/MEDIA_VERSION/${encodeURIComponent(mediaVersionId)}/reviews`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function selectMediaVersion(mediaVersionId: string, selectionType: string, baseUrl = ''): Promise<{ selection: Record<string, unknown> }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}:select`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ selection_type: selectionType }) }, baseUrl);
}

export async function createFrameAnchor(mediaVersionId: string, payload: { source_time_us?: number; source_frame_index?: number; position_mode?: 'FIRST_FRAME' | 'LAST_FRAME'; role_hint: 'FIRST_FRAME' | 'CURRENT_FRAME' | 'LAST_FRAME' }, baseUrl = ''): Promise<{ frame_anchor: FrameAnchor }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}:create-frame-anchor`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createKeyframeCandidate(mediaVersionId: string, shotId: string, baseUrl = ''): Promise<{ media: KeyframeCandidate }> {
  return requestJson(`/api/v1/media-versions/${encodeURIComponent(mediaVersionId)}:create-keyframe-candidate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ shot_id: shotId }) }, baseUrl);
}

export async function listJobs(projectId?: string, baseUrl = ''): Promise<{ items: Job[] }> {
  const query = projectId ? `?project_id=${encodeURIComponent(projectId)}` : '';
  return requestJson<{ items: Job[] }>(`/api/v1/jobs${query}`, undefined, baseUrl);
}

export async function createGenerationIntent(payload: { project_id: string; owner_type: string; owner_id: string; purpose: string; creative_goal: string }, baseUrl = ''): Promise<{ intent: GenerationIntent }> {
  return requestJson('/api/v1/generation-intents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listGenerationIntents(projectId?: string, baseUrl = ''): Promise<{ items: GenerationIntent[] }> {
  const query = projectId ? `?project_id=${encodeURIComponent(projectId)}` : '';
  return requestJson(`/api/v1/generation-intents${query}`, undefined, baseUrl);
}

export async function getGenerationIntent(intentId: string, baseUrl = ''): Promise<{ intent: GenerationIntent }> {
  return requestJson(`/api/v1/generation-intents/${encodeURIComponent(intentId)}`, undefined, baseUrl);
}

export async function planGenerationVariant(payload: GenerationVariantDraft, baseUrl = ''): Promise<{ plan: GenerationVariantPlan }> {
  return requestJson('/api/v1/generation-variants:plan', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createGenerationVariant(payload: GenerationVariantDraft & { plan_hash: string }, baseUrl = ''): Promise<{ variant: GenerationVariant }> {
  return requestJson('/api/v1/generation-variants', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function listGenerationVariants(intentId: string, baseUrl = ''): Promise<{ items: GenerationVariant[] }> {
  return requestJson(`/api/v1/generation-intents/${encodeURIComponent(intentId)}/variants`, undefined, baseUrl);
}

export async function getGenerationVariant(variantId: string, baseUrl = ''): Promise<{ variant: GenerationVariant }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}`, undefined, baseUrl);
}

export async function getGenerationVariantLineage(variantId: string, baseUrl = ''): Promise<{ items: GenerationVariant[] }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}/lineage`, undefined, baseUrl);
}

export async function deriveGenerationVariantPlan(variantId: string, payload: { operation: 'RESAMPLE_NEW_SEED' | 'RESUBMIT_PROVIDER_RANDOM' | 'EXACT_REPLAY' | 'PROMPT_BRANCH' | 'SOURCE_IMAGE_BRANCH' | 'PROFILE_BRANCH'; explicit_seed?: number; prompt_revision_id?: string; first_frame_media_version_id?: string; profile_version_id?: string; branch_reason: string }, baseUrl = ''): Promise<{ plan: GenerationVariantPlan & { draft: GenerationVariantDraft; diff: Record<string, unknown>; reproducibility: Record<string, unknown> } }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}:derive-plan`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function deriveGenerationVariantSeedBatch(variantId: string, payload: { seeds: number[]; branch_reason: string }, baseUrl = ''): Promise<{ batch: { parent_variant_id: string; count: number; plans: Array<GenerationVariantPlan & { draft: GenerationVariantDraft; diff: Record<string, unknown> }>; would_persist_variants: false; would_create_jobs: false } }> {
  return requestJson(`/api/v1/generation-variants/${encodeURIComponent(variantId)}:derive-seed-batch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function createPrompt(payload: { project_id: string; owner_type: string; owner_id: string; purpose: string; title: string; content_text: string; structured?: Record<string, unknown> }, baseUrl = ''): Promise<{ prompt: Record<string, unknown>; revision: PromptRevision }> {
  return requestJson('/api/v1/prompts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function branchPromptRevision(revisionId: string, payload: { content_text: string; structured?: Record<string, unknown> }, baseUrl = ''): Promise<{ revision: PromptRevision }> {
  return requestJson(`/api/v1/prompt-revisions/${encodeURIComponent(revisionId)}:branch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function getPromptRevision(revisionId: string, baseUrl = ''): Promise<{ revision: PromptRevision }> {
  return requestJson(`/api/v1/prompt-revisions/${encodeURIComponent(revisionId)}`, undefined, baseUrl);
}

export async function validateShotTransitionConstraint(constraintId: string, baseUrl = ''): Promise<{ validation: { constraint_id: string; status: 'COMPATIBLE' | 'WARNING' | 'BLOCKED'; blockers: Array<Record<string, unknown>>; warnings: Array<Record<string, unknown>> } }> {
  return requestJson(`/api/v1/shot-transitions/${encodeURIComponent(constraintId)}:validate`, { method: 'POST' }, baseUrl);
}

export async function createGenerationExperiment(payload: { intent_id: string; title: string; axes: Record<string, unknown[]>; max_parallel?: number; resource_estimate?: Record<string, unknown> }, baseUrl = ''): Promise<{ experiment: GenerationExperiment }> {
  return requestJson('/api/v1/generation-experiments', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function estimateGenerationExperiment(experimentId: string, baseUrl = ''): Promise<{ estimate: GenerationExperimentEstimate }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}/estimate`, undefined, baseUrl);
}

export async function confirmGenerationExperiment(experimentId: string, payload: { plan_hash: string; limit?: number; confirm_large_matrix?: boolean }, baseUrl = ''): Promise<{ result: Record<string, unknown> }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}:confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function expandGenerationExperiment(experimentId: string, limit = 20, baseUrl = ''): Promise<{ result: Record<string, unknown> }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}:expand`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ limit }) }, baseUrl);
}

export async function cancelRemainingGenerationExperiment(experimentId: string, baseUrl = ''): Promise<{ result: { experiment_id: string; status: 'CANCELLED'; cancelled: Array<Record<string, string>>; preserved: Array<Record<string, string>>; unexpanded_cancelled_count: number } }> {
  return requestJson(`/api/v1/generation-experiments/${encodeURIComponent(experimentId)}:cancel-remaining`, { method: 'POST' }, baseUrl);
}

export async function listSeasons(projectId: string, baseUrl = ''): Promise<{ items: Array<{ id: string; code: string; title: string }> }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/seasons`, undefined, baseUrl);
}

export async function listEpisodes(seasonId: string, baseUrl = ''): Promise<{ items: Array<{ id: string; code: string; title: string; production_status: string }> }> {
  return requestJson(`/api/v1/projects/seasons/${encodeURIComponent(seasonId)}/episodes`, undefined, baseUrl);
}

export async function getEpisodeProduction(episodeId: string, baseUrl = ''): Promise<{ episode: Record<string, unknown>; items: Array<Record<string, unknown>> }> {
  return requestJson(`/api/v1/episodes/${encodeURIComponent(episodeId)}/production`, undefined, baseUrl);
}

export async function localLLMStatus(baseUrl = ''): Promise<{ status: LocalLLMStatus }> {
  return requestJson('/api/v1/local-llm/status', undefined, baseUrl);
}

export async function h3CandidateRuntime(baseUrl = ''): Promise<{ runtime: H3Runtime; candidate_assets: Record<string, string> }> {
  return requestJson('/api/v1/h3/candidate-runtime', undefined, baseUrl);
}

export async function getG6Readiness(projectId: string, baseUrl = ''): Promise<{ readiness: G6Readiness }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g6`, undefined, baseUrl);
}

export async function planG6I2VProbe(projectId: string, baseUrl = ''): Promise<{ plan: I2VProbePlan }> {
  return requestJson(`/api/v1/projects/${encodeURIComponent(projectId)}/gates/g6/i2v-probe-plan`, undefined, baseUrl);
}

export async function listWorkflowVersions(baseUrl = ''): Promise<{ items: WorkflowVersionSummary[]; runtime_contacted: false }> {
  return requestJson('/api/v1/workflow-versions', undefined, baseUrl);
}

export async function getProductionCanvas(scopeType: 'EPISODE' | 'SHOT', scopeId: string, cursor = 0, limit = 100, baseUrl = ''): Promise<{ graph: CanvasGraph }> {
  return requestJson(`/api/v1/canvas/${scopeType}/${encodeURIComponent(scopeId)}?cursor=${cursor}&limit=${limit}`, undefined, baseUrl);
}

export async function saveProductionCanvasLayout(scopeType: 'EPISODE' | 'SHOT', scopeId: string, payload: { expected_revision?: number; positions: Record<string, { x: number; y: number }>; groups?: Array<Record<string, unknown>>; viewport?: Record<string, number> }, baseUrl = ''): Promise<{ layout: CanvasGraph['layout'] }> {
  return requestJson(`/api/v1/canvas/${scopeType}/${encodeURIComponent(scopeId)}/layout`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}

export async function preflightProductionCanvasRun(scopeType: 'EPISODE' | 'SHOT', scopeId: string, payload: { mode: 'NODE' | 'FROM' | 'TO' | 'RANGE'; from_node_id?: string; to_node_id?: string; max_nodes?: number }, baseUrl = ''): Promise<{ plan: { id: string; status: string; node_ids: string[]; blockers: Array<Record<string, unknown>>; estimate: Record<string, unknown>; submitted: false } }> {
  return requestJson(`/api/v1/canvas/${scopeType}/${encodeURIComponent(scopeId)}/runs:preflight`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }, baseUrl);
}
"""
    client_path.write_text(client_source, encoding="utf-8")
    print(f"wrote {openapi_path}")
    print(f"wrote {client_path}")


if __name__ == "__main__":
    main()
