export type RerollReasonCode =
  | "USER_REROLL"
  | "FACE_FIX"
  | "IDENTITY_FIX"
  | "COMPOSITION_FIX"
  | "MOTION_FIX"
  | "CONTINUITY_FIX"
  | "FRAME_BRIDGE_FIX"
  | "MODEL_COMPARE"
  | "PROMPT_TUNE"
  | "QC_AUTO_RETRY"
  | "OTHER";
